- reco/LST1_Hillas.py
- reco/RFDisp.py
- reco/RFEnergy.py
- reco/RFGHseparation.py
I corrected some bugs in RFEnergy.py and RFDisp.py, and added RFGHseparation.py.
This last script performs Energy/Disp reconstruction and uses the results for gamma/hadron separation using a Random Forest classifier.
> Add gamma-hadron separation script

- reco/LST1_Hillas.py
- removed all unused import (matplotlib, some astropy.__ , some ctapipe.__ , sys, copy)
- introduced argparse to deal with options
- filename
- particle_type
- outdir
- storeimg
- Removed all absolute paths
- Introduced default settings for options
- filename = gamma_test from ctapipe
- particle_type is guessed from filename or set to 'unknown'
- outdir = './results'
- storeimg = False
The code is cleaner and can be tested by anyone that has ctapipe installed with a simple 
``` python LST1_Hillas.py```
(before needed to manually change absolute paths)
> Cleaned import and used argparse for options

- reco/Disp.py
I added the functions alt_to_theta and az_to_phi to Disp.py, since they were deprecated from ctapipe.
I guess this is temporary until we find out how to use the coordinate transformations from ctapipe.
> Add functions for alt,az transformation to Disp.py

- magic-lst/add_pointingpos.cc
This script is to add 'pointing position' container to the MAGIC data file. It basically creates a separate file similar to that used as input, but only keeps the important information required and add pointing containers. Other auxiliary information can be stored as well. Once this newly generated root file is converted to an hdf5 file, the root file should be deleted to save disk space. This seems to me the easiest way to get the pointing information for the hdf5 file, considering the several corrections required on telescope pointing positions obtained from drive report.
> This code is to add pointing position container to MAGIC calibrated data file

- reco/calib_dl0_to_dl1.py
- reco/lst-recopipe.py
- reco/lst-trainpipe.py
- reco/lstpipe.py
- reco/parameters.py
- reco/plot_dl2.py
- reco/reco_dl1_to_dl2.py
- reco/reconstruction.py
- reco/transformations.py
- reco/utils.py
- reco/visualization.py
Hello everyone,
As some of you know, I was asked by Andrea Bulgarelli and the team dedicated to the CTA Real-Time analysis to provide a full working pipeline with all the codes from cta-lstchain.
They need to easily get events in DL3 format so they can store them in their database and apply their workflow. I tried to do something that will allow anyone to give as an input a raw LST1 event (or a simtelarray file with events) and have as an output DL3 data with all the parameters of the shower and its reconstrued energy, position and hadroness. 
To do so, I've rearranged all the scripts that we've been using in cta-lstchain/reco into modules with functions that can be easily called to perfom the different tasks from the chain.
I've created four basic modules(with very dull names, please …
> Modules and pipelines for an easy use of LST1 reconstruction chain

- lstchain/reco/dl0_to_dl1.py
- lstchain/reco/reco_dl1_to_dl2.py
- lstchain/visualization/plot_dl2.py
- scripts/lst-recopipe.py
- scripts/lst-trainpipe.py
I redid the old PR with the changes I needed to make all scripts run. 
- I included the if statement for the NaNs, it is necessary for running on larger simtelarray files other than the example one from ctapipe., until we decide how to manage it better.
- Just for aesthetics and coherence with cta-lstchain-extra: RFreg_disp -> RFreg_Disp
- Usage of "r0_to_dl1()" in lst-recopipe instead of get_events()
- Added a new argument to lst-recopipe, to limit the maximum number of events to analyze (for quick tests on larger simtelarray files)
- In visualization: plot_disp_ -> plot_disp, plot_E() -->  plot_e()
> Avoid NaNs in width, and small corrections

- scripts/lst-rfperformance.py
This is a script I had for some time, but which was not already merged. 
It is for testing the performance of the RF, with a larger "test" dataset than when using lst-recopipe. 
It's useful to tune the parameters of RF, testing new features os applying cuts.
> Add script to test the performance of RF

- lstchain/reco/utils.py
A typo was giving 3 a particle number to protons.
> Correcting a mistake in particle numbering 

- lstchain/io/lsteventsource.py
I got an error when I was trying to read zfits data in the following code.
`from lstchain.io.lsteventsource import LSTEventSource`
`from ctapipe.io import EventSeeker`
`source = LSTEventSource(input_url='.../LST1.1.Run00088.0000.fits.fz',max_events=30)`
`seeker = EventSeeker(source)`
`for i, event in enumerate(seeker):`
`    print('Event: {}'.format(event.r0.event_id))`
The error occured at `for i,event in enumerate(seeker)` and
error messages are the following.
`Traceback (most recent call last):`
`File "CheckCameraGeometry.py", line 21, in <module>`
`for event,i in enumerate(seeker):`
...
`File "/home/shunsuke.sakurai/AnalysisTool/anaconda/envs/cta-dev/lib/python3.7/site-packages/lstchain-0.1-py3.7.egg/lstchain/io/lsteventsource.py", line 93, in _generator`
`TypeError: __init__() …
> modified telescope description in lsteventsource.py

- lstchain/reco/utils.py
There was a typo. The source position was never actually computed.
> fixing bug with src_x, src_y

- utils/gammalearn/gl_utils.py
Modification of the way to load pretrained deep learning models. The only file impacted is utils/gammalearn/gl_utils.py.
> allow to load model not strictly indentical with the network

- lstchain/io/__init__.py
- lstchain/io/io.py
- lstchain/reco/dl0_to_dl1.py
- scripts/lst-recopipe.py
- scripts/merge_hdf5_files.py
This PR only adds simulation infos to DL1 files following the structure in v5 discussed in https://github.com/cta-observatory/ctapipe/issues/1059
Somehow fixes #119 .
As the DL1 structure is still being discussed, I think we can move forward with the simu info part to at least have this info available to create IRFs.
The events table structure stays untouched so the rest of the code will still work without any change.
I also modify the merge script to append the simu info from each merged file.
> Adding simulation info to DL1 files

- lstchain/reco/dl1_to_dl2.py
Replaced model and features variables in def train_disp_sign(). The R…F_model was set as a RandomForestRegressor, when it should be a RandomForesetClassifier, as the definition and documentation specifies. Also, the features were changed from regression_ to classification_features.
> Fix def train_disp_sign

- lstchain/io/lstcontainers.py
- lstchain/reco/dl0_to_dl1.py
Hi
Working on something different with @garciagenrique (thanks!), we discovered a small bug in the chain: the cleaning was not applied to the charge and pulse_time images before computing the timing parameters.
> applying cleaning to image before computing timing features

- .travis.yml
- README.md
- environment.yml
- Fixing ctapipe v0.7.0 in environment.yml
- Update travis config with two separate tests:
- one with fixed ctapipe v0.7.0 and ctapipe_io_lst v.0.1
- one testing ctapipe master and ctapipe_io_lst master.
This one is allowed to fail, meaning that it will not make the entire build fail but still warn us that the current code will not work with ctapipe master, allowing us to update it in the `ctapipe-master` branch.
- adding ctapipe_io_lst v0.1 to the install environment
- fixing python 3.7
> Fix ctapipe version to v0.7.0

- lstchain/io/io.py
Running things on the whole production, I realised that some fields in the mcheader do not actually need to be the same for files to be approved as mergeable.
Other small fixes/improvements might follow as I am testing things on large scales.
> Hotfix check mcheader

- lstchain/io/io.py
- scripts/merge_hdf5_files.py
- Resolve #177  with an option `no-image` for the merging
- improves the merging of DL1 files with a cleaner implementation (in precedent implementation, all nodes were copied from the first file to the merged file even if the user was passing `key_nodes` option).
PR #175 should be merged first.
> Merge HDF5 DL1 files without images

- lstchain/reco/dl0_to_dl1.py
Hello, this is the first pull request for my life :)
All survived pixels after image cleaning are used for hillas calculation with the current lstchain. If so, the estimation of shower axis could be bad when multiple islands exist, then all of the parameter could be useless.
With this branch, the number of island is calculated at first, then pixels in only main island which has maximum intensity is used for the parameter calculation later.
Please have a check.
> use pixels of only main island for hillas calculation

- lstchain/reco/tests/test_utils.py
- lstchain/tests/test_lstchain.py
A lot of tests are not passing just because the `rtol` in these unit test is too low.
(I don't know exactly what changed - I don't think it comes from lstchain - anyway, `rtol=1-4` is more than enough for these tests)
> lower rtol

- lstchain/pointing/__init__.py
- lstchain/pointing/pointings.py
This is the new PR following our previous discussion at #153. @FrancaCassol @vuillaut Please have a look. This is following the Component class as designed in ctapipe.
> Component class for adding pointing position using Drive Reports.

- lstchain/data/lstchain_standard_config.json
- lstchain/data/soft_cut_config.json
- lstchain/reco/dl0_to_dl1.py
My apologies, please have a look at this PR instead of #198
> add possibilty to write pe images in DL1 files

- lstchain/__init__.py
- lstchain/image/__init__
- lstchain/image/muon/__init__.py
- lstchain/image/muon/muon_analysis.py
- lstchain/image/muon/plot_muon.py
- scripts/lstchain_data_muon_analysis.py
- scripts/lstchain_data_muon_analysis_dl1.py
In this PR there is the script for muon real analysis following some of the discussions in #196 and the suggestions by @vuillaut.
- It contains everything related to the muon analysis, the stored quantities needed for the analysis and a tag for good or bad rings to be used in the analysis.
- It also contains an additional quantity that is the size outside of the ring, suggested by @moralejo to find muons with the image of a hadron together.
- Right now a non-optimized muon tagging is used, but @pillera will work on the first of the bulletpoints discussed [here](https://github.com/cta-observatory/cta-lstchain/pull/196#issuecomment-550236451) to have some functions for the muon tagging.
Some of the functions of this PR are copied from [the muon analysis of …
> Framework for the search for muons on real data

- lstchain/reco/dl0_to_dl1.py
- lstchain/tests/test_lstchain_mc_dl1ab.py
- scripts/lstchain_mc_dl1ab.py
- Read a HDF5 DL1 file, recompute parameters based on calibrated images and pulse times and a config file
- write a new HDF5 file
- Updated parameters are : Hillas paramaters, wl, r, leakage, n_islands, intercept, time_gradient
This is not the best approach since it recodes the computation of the parameters.
A better approach would be to code an `EventSource` for DL1 (but this will come with ctapipe DL1 Tools) and use the same pipeline once we have calibrated images, no matter their origin.
> Script to recompute DL1b parameters from a DL1 file

- lstchain/reco/dl0_to_dl1.py
- lstchain/scripts/onsite/onsite_create_calibration_file.py
- lstchain/scripts/onsite/onsite_create_drs4_pedestal_file.py
Fixing some small errors in recent updates that I discovered running scripts tonight.
> Fix analysis

- lstchain/reco/dl0_to_dl1.py
Until the timing information from UCTS is well tested and trustable, we will use only TIB time information for the time being (see #227)
> Get time info from TIB

- lstchain/pointing/pointings.py
- lstchain/reco/dl0_to_dl1.py
As @vuillaut reported in #231, the code related to the addition of pointing information to the data stream was terribly slowing down the performance. It was basically reading the drive report file for every event.
@labsaha and I modified the code in order for the drive file to be open only once at the beginning of the script and buffer it to be used later on.
@labsaha, @vuillaut and @rlopezcoto can you please take a look at the modifications?
> Optimize pointing scripts

- lstchain/reco/dl0_to_dl1.py
Skip the addition of pointing interpolated values when the timestamp of a given event is not available.
The code now checks if the timestamp is > 0 first, meaning that these time values are correct (presence flag is OK)
> Fix pointing bug #235

- lstchain/io/lstcontainers.py
- lstchain/reco/dl0_to_dl1.py
As mentioned in Issue #227 here I include the possibility of getting the timestamps from three different sources: UCTS, TIB counters and Dragon modules counters. **The three timestamps will be stored in the dl1 parameter tables.** Even if it is redundant information, for the time being, it will give us continuity in the time values since Dragon counters are quite stable and every now and then UCTS timestamp and TIB counters stop working fine.
Still, there is the question of which time info we should take by default. Right now it is TIB. 
What do you think @FrancaCassol @rlopezcoto @vuillaut @labsaha?
> Obtain time stamps from three different sources (UCTS, TIB and Dragon modules)

- lstchain/__init__.py
- setup.py
- version.py
- Updated `ctapipe_io_lst` version
- After [PR #22 from ctapipe_io_lst](https://github.com/cta-observatory/ctapipe_io_lst/pull/22), I have updated the way the version from lstchain is taken following @MaxNoe's solution
> Update ctapipe_io_lst version and __version__ of lstchain

- lstchain/data/lstchain_standard_config_keep_all_events.json
- lstchain/reco/dl0_to_dl1.py
Following #246 I implement here the possibility of not storing parameter tables if cleaning levels are set to 0 in order to keep all the events.
This will not be necessary once the refactoring is done as @vuillaut comments in #246
> Not writing DL1b if cleaning levels are set to 0

- lstchain/scripts/lstchain_data_create_time_calibration_file.py
I add the script to calculate the time calibration which was missing by mistake in the PR [https://github.com/cta-observatory/cta-lstchain/pull/248](https://github.com/cta-observatory/cta-lstchain/pull/248)
> Add time calibration script

- lstchain/data/lstchain_standard_config.json
- lstchain/reco/dl0_to_dl1.py
In order to be able to use any of the three available timestamps for pointing interpolation, I propose these changes (suggested by @rlopezcoto). I do not know if the nomenclature is the most convenient or not.
- Add the `timestamps_pointing` variable in the standard config file
- Use the timestamps defined in the config file (either `ucts`, `dragon` or `tib`) for pointing interpolation instead of having one of them hardcoded.
In this way, it will be possible to analyze old data using the required timestamps without having to change the code each time.
> Set the default timestamps in config file

- lstchain/pointing/pointings.py
- lstchain/reco/dl0_to_dl1.py
Regarding the pointing information. This PR now considers "Elevation" as  "zenith" angle. Then we calculate Altitude  which is equal to `"90 - zenith"`
We could have changed everything in the `pointings.py` file and get the altitude from that one. However, I want to keep is explicit that we get `Azimuth` and `Zenith` from the drive report. Hence I changed also to `dl0_to_dl1` file
> Updating the scripts to adapt zenith from the drive log

- lstchain/pointing/pointings.py
- lstchain/reco/dl0_to_dl1.py
This is for adapting the changes required for pointing information.
> Updating files for the correction to pointing positions

- lstchain/io/lstcontainers.py
- lstchain/io/tests/test_io.py
- lstchain/reco/dl0_to_dl1.py
Info are added both in image and params tables.
Fixes #275
> adding trigger info in dl1 files

- lstchain/pointing/pointings.py
Solve #282 
I assigned astropy units to AltAz pointing coordinates.
I tested setting later on `dl1_container.az_tel = azimuth.to(u.rad).value` in lstchain/reco/dl0_to_dl1.py and lstchain/reco/dl1_to_dl2.py was working fine with no errors. In principle, since `dl1_container.az_tel` container (idem for alt_tel) has already the units defined, there is no need to change the latter part.
I could reconstruct the Alt Az properly with actual pointing coordinates.
> Add astropy units to pointing AltAz

- .travis.yml
- README.md
- environment.yml
As the title suggests this changes the name of the conda environment from "cta" to "lstchain". 
I think "cta" is too generic. I hope this does not affects user who got the habit to do `conda activate cta`.
> Change conda env name

- lstchain/reco/dl1_to_dl2.py
Partly fix issue #285 
- avoid issue when alt_tel is not in the dl2 parameters
- load LST focal length from ctapipe (rather than having it hardcoded)
> alt_tel missing

- lstchain/data/lstchain_standard_config.json
- lstchain/reco/dl0_to_dl1.py
I updated the comment explaining the current status of time-stamp info in the code itself. Now, the GPS-WRS-UCTS system is providing timestamps with 50 ns accuracy which are still stored in the `ucts_time` container/variable instead of `gps_time`.
I did not change this and the other two TS (TIB and Dragon -based) are still being kept since UCTS TS info does not stably arrive at the data stream yet. Sometimes these TS are still missing.
@rlopezcoto, what do you think? Should we still keep the three TS or rename the `ucts_time` as `gps_time` already?
> Update comment with current status of TS info

- lstchain/reco/dl0_to_dl1.py
I did some cleanup of the code, but the main change is:
`image_extractor`  -> `extractor_product` in `dl0_to_dl1.py`
Solves #293
> Fix integrator call in dl0_to_dl1

- lstchain/pointing/pointings.py
- lstchain/reco/dl0_to_dl1.py
- lstchain/reco/dl1_to_dl2.py
- lstchain/reco/tests/test_utils.py
- lstchain/reco/utils.py
- lstchain/scripts/lstchain_mc_dl1_to_dl2.py
Fixes #285
- the pointing values are now `nan` instead of None in case of wrong timing info
- I propose a linear interpolation between pointing values when they are missing with the hypothesis that events are in order and come at a regular rate. Note that if a lot of values are missing, it might not be the best approach and feedback is welcome.
> Impute pointing values with linear interpolation

- lstchain/mc/sensitivity.py
- lstchain/spectra/crab.py
- lstchain/spectra/proton.py
Now the unit of e_true & e_reco is set to TeV because the unit of mc_energy & reco_energy in DL2 is TeV. Almost all the codes are working well, but I found following the only one part which have a problem.
e_aftercuts_w = np.sum(np.power(e_aftercuts, crab_par['alpha'] - mc_par_g['sp_idx']))
eff_area[i] = e_aftercuts_w.to_value() / n_sim_bin[i] * mc_par_g['area_sim'].to(u.m ** 2).to_value()
e_aftercuts_w is calculated with TeV unit, and n_sim_bin is with GeV.
So here I'd like to propose to set e_true amd e_reco to GeV at first.
> set unit of energy to TeV in sensitivity code

- lstchain/calib/camera/calibrator.py
To avoid problems as #293, in spite that we can now select a signal extractor thanks to #297, I would like to change the default signal extractor in the LSTCameraCalibrator. The reason is that the `NeighborPeakWindowSum` has not been working very well for real data, so I would rather have as a default `LocalPeakWindowSum` in case we do not set any in the configuration file.
L.21 is the main change, the rest is only code cleanup.
> Change default integrator

- lstchain/io/io.py
- lstchain/io/tests/test_io.py
There has been a lot of issues with file merging lately, even with MC.
Part of it is that reduction to DL1 or DL2 does not always happen perfectly and smart merging assumed so.
This PR fix a bit of the issue, by removing files that do not include all the necessary datasets from the merging list, instead of assuming they all should be merged.
If not smart merge, only the common datasets are merged.
> smarter merge

- lstchain/io/io.py
- lstchain/reco/dl0_to_dl1.py
Hello,
I produced simtel files where the name of some of the telescopes, some of the cameras was not defined. When I tried to convert them to dl1 I the following error:
`OSError: Table /instrument/telescope/camera/UNKNOWN already exists`
This PR fixes the issue (which was reported here): https://github.com/cta-observatory/cta-lstchain/issues/294
I also raised an explicit exception when trying to create an DL1 file which already exist. Otherwise it would fail later with some obscure error similar to the one above.
> Error when reading a simtel file with no defined telescope or camera name

- lstchain/scripts/lstchain_merge_hdf5_files.py
@vuillaut I moved PR #305 here because I messed it up between different branches.
I propose to include these lines in order to be able to merge all the files corresponding to a given run. If no run number is specified, the merging is performed as it was before.
I've made here the changes you requested:
- update help comment for run-number option
- use `os.path.join` instead of `+ '/' +`
Closing #305
> Merge run wise and sorted

- lstchain/io/lstcontainers.py
- lstchain/reco/dl0_to_dl1.py
After talking to @FrancaCassol about the `trigger_type` and its reliability, she suggested that, for the time being, we could also add the `ucts_trigger_type` to the DL1 data containers. 
This variable should not substitute the current `trigger_type`, but complement it for expert checks in the DL1 data.
> Add ucts trigger to the DL1 container

- lstchain/mc/mc.py
- lstchain/mc/sensitivity.py
- lstchain/mc/tests/test_mc.py
Here I'd like to implement the code for weighting MC gamma to LogParabola spectrum.
Main difference is:
- can select spectral shape for weighting, "PowerLaw" or "LogParabola" in mc/mc.py("rate", "weight")
- apply LogParabola in mc/sensitivity.py("find_best_cuts_sensitivity", "sensitivity")
Any comments are welcome.
> weighting MC gamma to MAGIC log-parabola spectrum

- environment.yml
Fixes conda warning:
```
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
```
> Add pipto env file

- lstchain/tests/test_lstchain.py
The test was relying on string internaling which might or might not happen.
> Fix version comparison in tests

- pyproject.toml
- setup.cfg
- setup.py
Reference for pyproject.toml and why we should have one:
https://www.python.org/dev/peps/pep-0518/
https://www.python.org/dev/peps/pep-0517/
https://snarky.ca/what-the-heck-is-pyproject-toml/
> Add pyproject.toml, move static options to setup.cfg, style

- lstchain/mc/sensitivity.py
- lstchain/mc/tests/test_senstivity.py
Due to the new version of gammapy (v0.17), `excess_matching_significance_on_off` function disappeared and now it is substituted by the following lines
> Update gammapy stat

- lstchain/reco/dl0_to_dl1.py
- lstchain/reco/tests/test_utils.py
- lstchain/reco/utils.py
As decided in #288, here is the workaround to transform Unix timestamps from TAI to UTC scale using `jd` format as an intermediate step. Whenever astropy v4.1 is ready we should simply use the new `unix_tai` format that automatically considers the leap seconds (current `unix` format does not). See #324.
As of now, with this transformation:
- event timestamps will be compared to the ones in the drive logs using UTC scale in both cases.
- UCTS, Dragon and TIB- based event timestamps will be stored in UTC scale (37 secs behind TAI scale) from now on.
> Transform unix timestamps from TAI to UTC scale

- lstchain/io/lstcontainers.py
- lstchain/reco/dl0_to_dl1.py
- lstchain/reco/dl1_to_dl2.py
- lstchain/visualization/plot_dl2.py
> Change unit of log_e_reco from GeV to TeV

- lstchain/_version_cache.py
- lstchain/image/muon/muon_analysis.py
- lstchain/image/muon/tests/test_muon_analysis.py
* get_muon_ring_center actually transformed pixel positions into nominal frame
* It needlessly transformed into nominal frame (which needs an array pointing positoin), changed that to `TelescopeFrame`, which is the same if there is no divergent pointing and does not need an array pointing direction
* some style improvements
> Muons: Fix wrong rotation in CameraFrame

- lstchain/scripts/lstchain_dl1_to_dl2.py
- lstchain/scripts/lstchain_mc_dl1ab.py
- lstchain/scripts/lstchain_mc_r0_to_dl1.py
- lstchain/scripts/lstchain_mc_r0_to_dl2.py
- lstchain/scripts/tests/test_lstchain_scripts.py
- unused import
- better path management
- an issue with main in r0 to dl2 + test
> fix a couple of things with scripts

- lstchain/reco/r0_to_dl1.py
It seems that the `HDF5TableWriter` is reading the filters from the file if it already exists.
However, the writer is able to use filters per dataset, hence I could overwrite them after its instantiation. 
This will allow the compression and save ~10% of disk use.
Solves #352
> forcing filters for dl1 dataset to enable compression

- environment.yml
1. Eliminate `protozfitsreader` since it is already included in [ctapipe_io_lst](https://github.com/cta-observatory/ctapipe_io_lst/blob/240ae6f8ce3b7c09ea855f779077d592f4049ec5/py3.6_env.yaml#L34)
2. As found by @MaxNoe, include the installation of `ctapipe_io_lst` that conserves the automatic versioning from git
> Modify environment

- .travis.yml
- environment.yml
- setup.cfg
Travis was not actually testing different python versions, because we install anaconda and don't make sure which python version was installed using anaconda, so it was always what came with miniconda.
Currently 3.7.
> Fix python versions on travis

- setup.py
Note: I did not add ctapipe_io_lst as this would prevent the pypi upload, as currently ctapipe_io_lst cannot be uploaded to pypi.
> Add missing requirements to setup.py

- lstchain/reco/r0_to_dl1.py
This fixes problem with #390, in case the dir string is empty, ''
> Fix in muon file path building, in case directory is current one ('')

- lstchain/scripts/lstchain_dl1_to_dl2.py
With #384, and discussing what was the best way to write the DL1 info and which one to write in the DL2 file, we actually forgot to write the DL2 information (!)
Also now, if src_dependent parameters are present in the DL1 file, they are removed in the DL2 one (regardless of whether they are used or not in the dl1_to_dl2 passage)
> Solve dl2 and dl1_src_dependent writing

- lstchain/__init__.py
- setup.py
Solution to work out the problem with the matplotlib style/backend that was described in #401. While this is worked out, these lines should force the matplotlib style to the 'default' one, that was working before for all the plotting.
> Solve matplotlib style problem that was making labels non-legible

- lstchain/datachecks/dl1_checker.py
Use always trigger_type to identify interleaved pedestals, because ucts_trigger_type seems to be always wrong (whereas trigger_type is sometimes correct)
Fix font sizes in the DL1 data check plots, that had become messed up due to some other update in lstchain (not sure which one)
> Use only trigger_type to identify pedestal events

- lstchain/datachecks/dl1_checker.py
This fixes the safeguard against merging a run-wise datacheck_dl1*.h5 file again with the subrun-wise datacheck_dl1*.h5 files of which it is composed.
> Safeguard when merging datacheck_dl1 files

- lstchain/calib/camera/calibration_calculator.py
Remove the check of UCTS trigger in interleaved pedestal events, because often wrong.
> Fix use of UCTS trigger in interleaved pedestals events

- lstchain/io/io.py
- lstchain/scripts/lstchain_merge_hdf5_files.py
Add a `--pattern` option and use glob to filter files.
I used it with `-p 'dl1_*.h5'` to fix #412 
With that it works nicely and provides roughly 6 Million events instead of the 4 Million with 0.4.4 and the erros in subruns 80+
> Add pattern argument to merge hdf5, add progress bar

- lstchain/datachecks/containers.py
- lstchain/datachecks/dl1_checker.py
Solves issues occurring when muon files have no entries, as well as a strange pyplot.hist2d error, which failed very few times (I don't know why) when inputs were pandas data series (instead of numpy arrays).
This hopefully addresses issues #414 and #416. Tested it on some of the failing files, I think it should work for all of them.
> Safeguard in DL1 data check against empty muon files + solved pyplot related issue

- lstchain/data/lstchain_src_dep_config.json
- lstchain/scripts/lstchain_dl1_to_dl2.py
There was a small bug on the `lstchain_dl1_to_dl2.py` script that did not allow to process data using src_dependent analysis. I also got problems with `data_src_dep.set_index('index', drop=True)` why was this line there @SeiyaNozaki?
I also updated the src_dependent input card, that still had some old variables defined.
> Fix src dependent

- lstchain/reco/tests/test_utils.py
- lstchain/reco/utils.py
- lstchain/tests/test_lstchain.py
This PR fix the problem in the method computing camera_to_sky for event to take properly into account the time of the observation in the computation.
For the moment, just use time if provided and the default obs time in utils if not printing a warning.
I think the solution to use HA/DEC for MC event instead of RA/DEC should be done in another method when you compute ra/dec for those SkyCoords. For example, if I read correctly to compute the HA from RA, we need to extract the sideral time from the obs time and the location.
```obstime = sky_coords.obstime.value
scale_time = sky_coords.obstime.scale
longitude = sky_coords.location.longitude
latitude = sky_coords.location.latitude
time=Time(obstime, scale, location=(longitude, latitude)
HA = sky_coords.icrs.ra.to("hourangle") …
```
> Fix method camera_to_sky for real events

- lstchain/data/lstchain_src_dep_config.json
- lstchain/data/lstchain_standard_config.json
- lstchain/data/soft_cut_config.json
- lstchain/reco/r0_to_dl1.py
- lstchain/reco/tests/test_r0_to_dl1.py
> DL1 scaling

- lstchain/calib/camera/calibration_calculator.py
After discussion with @moralejo, it seems that we do not want to take as reference the flat-field time for the pulse times. This is actually what we have done since we apply the drs4 time corrections. 
In this PR I remove this global shift. The times will be only drs4 corrected and flat-fielded.
> Remove shift of times toward the flat-field time

- lstchain/paths.py
- lstchain/scripts/lstchain_dl1_to_dl2.py
- lstchain/tests/test_paths.py
When using `r0_to_dl1_filename`, it seems another segment is removed by using `with_suffix` .
```
>>> from lstchain.paths import r0_to_dl1_filename
/fefs/aswg/workspace/seiya.nozaki/Install/anaconda3/envs/lst-dev/lib/python3.7/site-packages/corsikaio/subblocks/dtypes.py:20: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
return np.dtype(dict(**dt))
>>> r0_to_dl1_filename("/fefs/onsite/data/20200117/LST-1.1.Run01817.0000.fits.fz")
PosixPath('/fefs/onsite/data/20200117/dl1_LST-1.1.Run01817.h5')
>>> r0_to_dl1_filename("/fefs/aswg/workspace/MC_common/corsika6.9_simtelarray_2018-11-07/LST4_monotrigger/prod3/gamma/gamma_offaxis0.4deg_20190415/North_pointing/Data/gamma_20deg_0deg_run1 …
```
> bug fix for the replacement of dl1 suffix

- lstchain/data/onsite_camera_calibration_param.json
- lstchain/visualization/plot_drs4.py
Keep default trailets values for the selection of the R0 waveform samples to be used for the R1 waveform. Before the firmware upgrade of November, values were
"r1_sample_start": 2,
"r1_sample_end": 38
After, they should be: 
"r1_sample_start": 3,
"r1_sample_end": 39
A test did not show major changes in the calibration results
> Correct LSTR0Corrections cards for calibration script

- .travis.yml
- environment.yml
- setup.py
Setting up new environment and updating travis and environment variables with the new software versions.
Notice that this PR has as a target the branch `lstchain_ctapipe0.8`, the development branch that will contain the changes to update to ctapipe v0.8
> Set up environment of the lstchain_ctapipe0.8 branch

- lstchain/data/lstchain_src_dep_config.json
- lstchain/data/lstchain_standard_config.json
- lstchain/data/soft_cut_config.json
- lstchain/io/lstcontainers.py
- lstchain/mc/sensitivity.py
- lstchain/reco/utils.py
- lstchain/scripts/lstchain_mc_dl1ab.py
To include the container name (leakage) at the beginning of the variable name.
> Modify leakage variable names

- lstchain/calib/camera/calibrator.py
- lstchain/reco/r0_to_dl1.py
This is a first fix for the camera calibration, that permit to apply the calibration
(other fixes related to the calibration containers and calibration calculation can come in a second PR)
> Add subarray to calibration class

- lstchain/io/lstcontainers.py
After sorting the lines, the last one ('LSTEventType') did not have a comma and when sorting, it moved to the middle of the list, throwing an error.
> Fix lstcontainers call

- lstchain/io/io.py
- lstchain/reco/r0_to_dl1.py
Double the info (small overhead) for now to not change the data format.
This is temporary for lstchain v0.6
> write array info a la ctapipe v0.8

- lstchain/calib/camera/calibration_calculator.py
Remnant of #463. 
As reported in https://github.com/cta-observatory/cta-lstchain/pull/463#pullrequestreview-444682317, there were still some `charge_correction` remnants after the `get_charge_correction` function had been eliminated.
> Remove charge correction

- lstchain/io/io.py
- lstchain/io/tests/test_io.py
Necessary as long there is no DL1 event source
> add functions to read instrument info from DL1 file

- lstchain/calib/camera/time_correction_calculate.py
I found bug in `time_correction_calculate.py`- wrong method name to call.
> fix time_correction method name

- lstchain/scripts/lstchain_mc_rfperformance.py
- lstchain/scripts/tests/test_lstchain_scripts.py
- lstchain/tests/test_lstchain.py
- lstchain/visualization/plot_dl2.py
There were two problems that were making the tests from the `scripts` folder not to pass:
- If the `fake_proton_file` was created from that folder, since we relied on absolute paths wrt the `lstchain/tests` folder.
- If the number of `selected_gammas` in `lstchain_mc_rfperformance` was 0, the code was breaking.
Now tests pass also from inside the `scripts` folder and regardless of the input files used.
> Fix lstchain_rfperformance tests

- lstchain/visualization/tests/test_camera.py
we've been experiencing some travis error related to the camera display, that could not be reproduced locally. I'll copy it down for bookkeeping. I've been doing some tests and apparently the order of the tests matter. For some reason, if we run the `test_overlay_source` after the `test_overlay_disp_vector`, the error appears. It is not clear to me yet what is the origin, but this PR fixes it.
```
_____________________________ test_overlay_source ______________________________
def test_overlay_source():
geom = CameraGeometry.from_name('LSTCam')
image = np.random.rand(geom.n_pixels)
>       display = CameraDisplay(geom, image)
lstchain/visualization/tests/test_camera.py:23: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ …
```
> Fix travis errors related to test_overlay_source

- lstchain/scripts/lstchain_data_create_time_calibration_file.py
After discuss with @moralejo I have created PR for new version of script to create time calibration file with multi subruns. 
To do it: `python lstchain_data_create_time_calibration_file.py --input-file 'LST-1.1.Run01625.000*.fits.fz' --output-file time_calib_1625_multi.h5 --max-events 60000`
> allow to use subruns to create time calib file

- lstchain/datachecks/containers.py
- lstchain/datachecks/dl1_checker.py
- lstchain/image/muon/muon_analysis.py
Removed the duplicated masks for the DL1 parameters and DL1 images tables,
since they have one-to-one corresponding rows. Besides, code did not work
because images table now lacks event_id
> Removed the duplicated masks for  DL1 parameters & images

- lstchain/calib/camera/calibrator.py
Current version does not work for new (r0 ro dl1 stage in real data). This seems to fix it.
> Fixed initialization of charge and peak_time arrays

- lstchain/datachecks/dl1_checker.py
Don't fill anything on tables (of pedestals, flatfield or cosmics) unless everything can be filled. This avoids problems in the later merging of tables, when some of them were partially filled.
> Avoid partial filling of tables (of pedestals, flatfield or cosmics)

- lstchain/io/lstcontainers.py
- lstchain/reco/r0_to_dl1.py
gps time is not used anywhere and is now written as nan value in dl1, causing errors down the line.
Same error can get caused by `mc_core_distance` filled by nan
> remove gps_time

- setup.py
Following the discussion on slack:
https://ctapipe.slack.com/archives/C0160M3K362/p1596115158284400
```py3
astropy>=3,<5
```
may install astropy v3.2.3, which is not compatible with lstchain >= v0.6, so this should solve the problem
> Update to astropy v4

- lstchain/calib/camera/calibration_calculator.py
- lstchain/data/lstchain_standard_config.json
- lstchain/data/onsite_camera_calibration_param.json
- Modify the global calibration scaling factor including:
1. The factor due to the different integration window in cosmics (8 ns) and laser events (12 ns). We use the values estimated on data by Yukiho (see [slide 12](https://indico.cta-observatory.org/event/2853/contributions/24597/attachments/17750/23853/ChargeRecoYukiho20200629.pdf)) :  [HG,LG]=[1.088,1.004]
2. The average estimated effect on the gain due to the DRS4 time sampling inhomogeneities and laser variation:  [HG,LG]=[1.05,1.10]  
- Update the excess noise factor to the most recent estimated value (Fˆ2=1.222)
It will remain a small underestimation of the light with respect to MC due to the 12 ns window, taken here as reference
> Change default calibration scaling factor tp account for different integration windows and the effect of sampling inhomogeneities

- environment.yml
- lstchain/io/io.py
- lstchain/io/tests/test_io.py
- lstchain/scripts/tests/test_lstchain_scripts.py
> read dl2 and sim info into pyirf internal format

- lstchain/image/muon/muon_analysis.py
- lstchain/reco/r0_to_dl1.py
- lstchain/scripts/lstchain_dl1_muon_analysis.py
The muon mc energy that was being written per event was the full array of energies instead of the energy of the event, so no the `mc_energy` of the event is now passed to the `fill_muon_event` function whenever we have MC data, and `-1` is passed when we are analyzing real data.
> Fix filling of muon mc energy in the muon output

- lstchain/reco/dl1_to_dl2.py
- lstchain/reco/tests/test_utils.py
- lstchain/reco/utils.py
- lstchain/scripts/lstchain_dl1_to_dl2.py
- lstchain/tests/test_lstchain.py
@morcuended I wanted to make an update on your PR #525 , made one in your branch, then finally rebased from yours considering @moralejo comments, hence the history of commits here.
Finally, your first idea was in the right direction.
> Filter events not droping nan on all columns anymore

- lstchain/reco/r0_to_dl1.py
There was a bug in the implementation of the logging of time information when UCTS is not available. It was always showing the message "Not valid UCTS timestamp found" even though the time information was present. This fix should prevent that message from appearing always.
> Fix time message when no UCTS time info is available

- lstchain/data/lstchain_standard_config.json
The gain scaling factor (see #516) have been re-estimated with higher statistics and more constraint fit 
(see  [here](https://indico.cta-observatory.org/event/3052/contributions/25956/attachments/18098/24444/CalibrationScalingFactors_5_10_2020.pdf) for details)
The new estimated values are [HG,LG]=[1.08,1.09] (previously were [1.05,1.10]), therefore the new global scaling factors are estimated as [HG,LG]=[1.08,1.09]*[1.088,1.004] = [1.18,1.09]  (previously were [1.142,1.104])
> Update the calibration scaling factors based on the new estimation of the gain scaling factors due to sampling correction

- lstchain/scripts/longterm_dl1_check.py
Corrected a last-minute change introduced (and not properly tested) in longterm_dl1_check.py
Otherwise the long-term DL1 data check fails in runs in which no pedestal info is present.
Also introduced (just in case) a file existence check for muon files, though this should not be needed now as files always exist even of they contain no muons.
> Changed wrong exception type by generic one

- lstchain/io/io.py
There was a bug while trying to run lstchain_mc_r0_to_dl1 script to prod5 MC. [issue #514](https://github.com/cta-observatory/cta-lstchain/issues/514) 
I modified `write_array_info_08` function like `write_array_info` function and became to be able to process the prod5 MC.
> Fix an error while processing prod5 MC (updated)

- setup.py
Current installation wheel (`conda env update -f env.yml` plus `pip install .`) installs 'astropy 4.0.1.post1'. And `pyirf` need astripy version 4.2.
> update astropy version

- lstchain/io/io.py
- lstchain/reco/r0_to_dl1.py
- lstchain/tests/test_lstchain.py
`event_id` and `obs_id` disappeared from the dl1 image table with ctapipe v0.8
add simple test to check if these parameters are present in the file after r0 to dl1
> adding back event_id and obs_id in dl1 tables

- lstchain/reco/tests/test_utils.py
- lstchain/reco/utils.py
If the column name for the filtering does not exist, the filtering is simply not applied without warning.
I myself sometimes wasted time as I didn't notice the filtering didn't work due to the change of hillas parameters' names.
This PR is to raise an error when keys for the filtering don't exist.
> Raise an error when keys for the filtering don't exist

- README.md
- lstchain/io/lstcontainers.py
- lstchain/reco/r0_to_dl1.py
Some information about the events were not written in case the Hillas Parameterisation failed, although we should keep this info (otherwise there is no point keeping the event).
Interestingly enough, there was a comment in the code in this sense already:
> The condition below should now be true for all events, this dl1_container.fill_event_info(event) is a relic of the previous approach in which only survivors of cleaning and parametrization were further processed.
I also make some related cleaning.
- reset dl1 container before to fill it
- always fill event info (event id, obs id) and missing mc info: `mc_type` and `mc_core_distance`
- move some dl1 computation in get_dl1 or in fill_mc
- fill MC info whether or not Hillas parameters are computed
- treat events independently of the …
> fill event info even if Hillas parameters could not be computed

- lstchain/tests/test_lstchain.py
As discussed in #554 , I got an error when computing time parameters of events with `n_pixels` of 1 during pytest.
It seems `keep_isolated_pixels` is `false` in custom configuration used in `test_lstchain.py`.
I created this PR to use standard configuration for pytest instead of the custom configuration.
It should solve this issue, and useful to check if the default configuration is valid.
> Use standard configuration file for pytest

- environment.yml
- lstchain/mc/sensitivity.py
- lstchain/mc/tests/test_senstivity.py
- setup.py
Fix errors due to the name changing of function `excess_matching_significance` -> `n_sig_matching_significance` in gammapy v0.18
Also, the significance definition changed and there were some modifications on the results, so tests were also modified.
> Fix gammapy error due to the new version

- .github/workflows/ci.yml
- .github/workflows/deploy.yml
- README.md
With the new pricing model, travis became basically unusable for cta-observatory. This switches to using github actions.
I for now removed the tests on ctapipe master because:
a) Github Actions is missing the "allowed-failures"
b) They were already failing always since lstchain is now two major versions behind the currrent ctapipe release, so it doesn't make sense to test vs. master.
> Switch to github actions

- lstchain/data/lstchain_src_dep_config.json
- lstchain/data/lstchain_standard_config.json
- lstchain/data/soft_cut_config.json
- lstchain/mc/tests/test_senstivity.py
As discussed some time ago, with the changes in Data/MC regarding integration windows and correction factors, the number of islands between data and MC was not matched anymore when using the standard cleaning settings, so there was a mismatch in background rates after classification noticed by @moralejo 
The temporary solution is to remove the `n_islands` from the Random Forest training
> Remove n_islands from config files

- lstchain/scripts/lstchain_dl1ab.py
Trying to fix #543 for real data since there are no disp related parameters in those files. They are only in MC files
I removed the re-calculation of `r` because it is already done by the `hillas_parameters` function.
> Update only disp params if already present in the file

- environment.yml
- setup.py
After #509 was merged, there is an import of `toml` in:
https://github.com/cta-observatory/cta-lstchain/blob/b8e30215c5079cf1e456be2831a19409221b7eb0/lstchain/scripts/lstchain_post_dl2.py#L6
and the package is not included as a dependency
> add missing toml from environment/setup

- lstchain/io/lstcontainers.py
- lstchain/reco/dl1_to_dl2.py
Issue:
- Some of the parameters are initialized with a default value = -1.
- Even in case of issues with the computation of these parameters, they can be used for training without causing issues (the values are valid predictions)
- Training and inference would not raise any error and warning but make useless predictions
I encountered the problem when using `dl1ab`, the `mc_type` would be set to -1 for some events and thus the RF would predict 3 classes and the gammaness would not be assigned to the right class.
So I also add an error raise in case of more than 2 predicted classes, which should never happen in current setup.
> Filters on mc_type for RF

- README.md
Since this is getting confusing for people, it is probably better to include it in the README for the time being, at least until it is modified in the ctapipe documentation.
> Modify README to include information on how to perform PRs

- lstchain/data/lstchain_standard_config.json
- lstchain/reco/r0_to_dl1.py
- lstchain/scripts/lstchain_data_r0_to_dl1.py
- lstchain/tests/test_lstchain.py
LST event source configuration is now in the json file (though command-line options, if present, override the settings in the file). So there should be no change of behavior. Now one can select the preferred trigger tag (ucts or tib) by setting it in the file.
> Move configuration of LST event source to json file

- lstchain/datachecks/dl1_checker.py
UCTS and TIB times are not propagated to DL1 now (neither are they in the standard ctapipe DL1 to which we will eventually move), so I remove the related plots.
> Removed unnecessary plots about TIB and UCTS times in DL1 check

- environment.yml
- setup.py
Maybe we could explicitly include ctapipe `v0.10.5` as well? No big changes from v0.10.4, right?
> Update ctapipe_io_lst and ctapipe versions

- lstchain/data/lstchain_standard_config.json
- lstchain/reco/r0_to_dl1.py
- lstchain/scripts/lstchain_dl1ab.py
Add the possibility to set a simple time constraint in the cleaning: right before image parametrization (i.e. after the charge-based cleaning) we require each pixel to have at least a neighbor with peak time within delta_t of the pixel's peak time.
> Time constrained cleaning

- lstchain/data/lstchain_src_dep_config.json
- lstchain/data/lstchain_standard_config.json
- lstchain/reco/r0_to_dl1.py
- lstchain/scripts/tests/test_lstchain_scripts.py
After discussion in #628, we finally decided for a standard cleaning defined by:
- picture threshold = 6
- boundary threshold = 3 
- sigma = 2.5
- time delta cleaning = 2
- min_number_picture_neighbors = 2
as it is included now in the configuration of `tailcuts_clean_with_pedestal_threshold`. There is still the point raised by @moralejo that `tailcut` would still be applied at the `r0_to_dl1` level, but in principle we need to compute the events using the proper cleaning by running the `lstchain_dl1ab.py`
Other places where the regular `tailcuts_clean` is used are:
- `lstchain/reco/volume_reducer.py`
- `lstchain/image/muon/muon_analysis.py` -> here a [hardcoded [10, 5] cleaning is applied](https://github.com/cta-observatory/cta-lstchain/blob/5183119f3fb732163d03bb463dd4efdac3122f48/lstchai …
> Update default cleaning levels 

- lstchain/reco/r0_to_dl1.py
The present code overwrites the level A calibration as soon as a Level B calibration event is ready, this is not what we want at this level
> Fix mixing of Level A and Level B calibration

- lstchain/io/io.py
- lstchain/reco/r0_to_dl1.py
Excludes non-existing columns from attempt to write, thus suppressing the corresponding warnings
> Suppress Column X in Table Y is not writable warnings

- lstchain/io/event_selection.py
- lstchain/tools/lstchain_create_irf_files.py
- lstchain/tools/tests/test_tools.py
Fixing Full Enclosure IRF by resolving a mixup between 'mc_type' and 'irf_type' and a small error in calculating source_offset_bins for PSF.
> Fix Full Enclosure IRF

- lstchain/calib/camera/pixel_threshold_estimation.py
Fix Unusable pixels error in dl1ab #669.
According to @FrancaCassol and @moralejo suggestion, I took calibration_id from `f.root.dl1.event.telescope.monitoring.pedestal.col('calibration_id')` to got unusable_pixels.
This solve problem with production, but such data  as run 02927, sub-run 0164  have wrong interleaved pedestal (pedestal from calibration run instead from data run). Do you have any idea how to solve it?
> Unusable pixels in dl1ab

- README.md
This is not needed anymore since we have the conda-forge packages.
> Remove obsolete macos instructions

- lstchain/reco/dl1_to_dl2.py
The events were not filtered before applying the models, leading to an issue when `nan` values were in the data in the latest production, nicely reported by @chaimain and @garciagenrique.
It also means that the filters were not applied in case only applying the dl1_to_dl2 step (with stricter filters than when dl1 are created).
> filter events before applying models

- lstchain/calib/camera/pixel_threshold_estimation.py
Change in order to use the beginning of night calibration for the pedestal events used for threshold estimation (as done for the cosmics)
> Use Level A calibration for interleaved pedestals for threshold estimation 

- lstchain/tools/lstchain_create_irf_files.py
It would be great to allow more complex names for IRF files.
For example, in the production, we use tags such as `20210403_v0.7.1_prod5_trans_80_local` in the names that include the lstchain version. In this case, we would end up with `20210403_v0.fits.gz` as filename.
> allow more complex naming of irf files

- lstchain/scripts/lstchain_dl1ab.py
This PR recovers metadata added to DL1 files during the initial `r0_to_dl1` process, that were lost when applying `lstchain_dl1ab.py` script.
> Recover metadata in DL1 files

- lstchain/calib/camera/drs4.py
- lstchain/scripts/lstchain_data_create_drs4_pedestal_file.py
With the change of just using the calibration inside the `LSTEventSource`
instead of manually performing the timelapse calibration inside the
pedestal script, it is necessary to look at the r1 waveform, not the r0
waveform.
> Use r1 waveform to calculate pedestal, fixes #767

- lstchain/conftest.py
- lstchain/scripts/lstchain_create_run_summary.py
- lstchain/scripts/tests/test_lstchain_scripts.py
This also switches to using pytests tmp dir factories, which enables looking at the files produced in tests after they failed
> Fix run type in run summary, fixes #775

- README.md
I ran into a problem with a package version and @maxnoe suggested setting `export PYTHONNOUSERSITE=1` which can be automatically done by doing `conda env config vars set PYTHONNOUSERSITE=1 -n <environment_name>`
> Add instruction to set PYTHONNOUSERSITE in conda env

- lstchain/io/io.py
- lstchain/scripts/tests/test_lstchain_scripts.py
to allow reading the table directly with `ctapipe.io.read_table`
```
from ctapipe.io import read_table
from lstchain.io.io import dl1_images_lstcam_key
read_table('dl1_gamma_test_large.h5', dl1_images_lstcam_key)
```
leads  to:
```
NameError: ``where`` must start with a slash ('/')
```
> absolute paths to tables

- lstchain/io/__init__.py
- lstchain/io/io.py
- lstchain/io/tests/test_io.py
- lstchain/scripts/lstchain_dl1ab.py
- lstchain/scripts/lstchain_merge_hdf5_files.py
- lstchain/scripts/tests/test_lstchain_scripts.py
This PR simplifies and improves merging of HDF5 files by having a single `auto_merge_h5files` function. This function checks that HDF5 files to merge are compatible for merging by looking at their metadata as well as simulation info and histograms for MC files. 
These checks were also performed by similar function `smart_merge_h5files`, which has been removed. Though this function could merge *only* a list of more than one file, `auto_merge_h5files` function can also create a new file from the content of another one, which is how it is used in `lstchain_dl1ab.py` script. 
`auto_merge_h5files` also keeps existing global metadata in HDF5 files as well as potential existing attributes of their internal tables.
> Refactor and simplify merging of HDF5 files

- lstchain/scripts/onsite/onsite_create_calibration_file.py
- lstchain/scripts/onsite/onsite_create_drs4_pedestal_file.py
- lstchain/scripts/onsite/onsite_create_drs4_time_file.py
- lstchain/statistics.py
- lstchain/tests/test_statistics.py
- lstchain/tools/lstchain_create_drs4_pedestal_file.py
- lstchain/tools/tests/test_create_drs4_pedestal_file.py
Note that this does not work yet, it needs a new version of `ctapipe_io_lst` (providing the get_spike_A_positions method)  
Advantages over the current tool:
1. Skip events with unknown `last_readout_time` so that the timelapse correction is properly applied for all samples
2. By default skip 10 samples in front and 1 at the end (current script 11 int front, none at the back)
3. Skips spikes for baseline estimation
4. Estimates the 3 spike heights
5. Provides count, mean and std per gain, pixel, capacitor for baseline, spike samples 1, 2, and 3
6. Output is a compressed hdf5 file for now, we can discuss the best format / structure inside
> Add tool to extract drs4 baseline and spike heights

- lstchain/scripts/onsite/onsite_create_calibration_file.py
- lstchain/scripts/onsite/onsite_create_calibration_files_with_batch.py
Giving run numbers explicitly did not work due to the wrong type of the arguments
> Fix types of arguments in onsite calibration script

- lstchain/scripts/lstchain_data_r0_to_dl1.py
Needs new release of `ctapipe_io_lst` to work.
Is this needed elsewhere or only in `lstchain_data_r0_to_dl1`?
> Add option for pedestal ids file to lstchain_r0_to_dl1

- lstchain/io/io.py
- lstchain/scripts/lstchain_data_create_drs4_pedestal_file.py
- lstchain/scripts/lstchain_data_create_time_calibration_file.py
- lstchain/scripts/lstchain_merge_hdf5_files.py
- lstchain/scripts/onsite/onsite_create_drs4_pedestal_file.py
- lstchain/scripts/onsite/onsite_create_drs4_time_file.py
- lstchain/tools/lstchain_create_drs4_pedestal_file.py
This PR sets the display of the progress bar by default for running interactively calibration and merging scripts and adds `--no-progress` option for running in batch disabling the display of the progress bar.
It also includes the missing `--no-progress` option to the onsite calibration scripts.
> Display progress bar by default and add --no-progress option to run in batch mode

- environment.yml
- setup.py
After the bugfix related to event time and ucts jump in ctapipe_io_lst, we discussed that it might be best to make a new lstchain release explicitly requiring the version with the fix.
> Require at least ctapipe_io_lst 0.13.2

- docs/lstchain_api/visualization/index.rst
I guess this was committed by mistake or does it have a purpose @vuillaut ?
> Remove empty plot_irfs.py

- .github/workflows/ci.yml
- .gitignore
Gammapy 0.18 had a broken `pyproject.toml` resulting in building against a too new numpy version. This fixes it by circumventing the pep517 build and manually installing the build requirements for gammapy.
> Fix gammapy compilation in docs CI, fixes #842

- lstchain/datachecks/containers.py
- lstchain/scripts/longterm_dl1_check.py
Make sure not to double-count the number of UCTS jumps occurring in a run. Previous version counted each jump again in every subsequent subrun.
> Correct number of ucts jumps

- lstchain/io/io.py
- lstchain/scripts/tests/test_lstchain_scripts.py
This PR fixes issue #839 setting the value of the `root.source_filenames.filenames`array to the last list of filenames used when merging files.
> Set list of source filenames to last used

- lstchain/io/__init__.py
- lstchain/io/io.py
- lstchain/io/tests/test_io.py
- lstchain/scripts/lstchain_dl1ab.py
I factored out the copying part into it's own function from `auto_merge_h5files`, added the copying of group attrs and replaced the now unneeded call to `auto_merge_h5files` with a single file in dl1ab with the new `copy_h5_nodes` function.
I also removed the use of h5py to get the dataset keys to use tables instead, as we do for everything else hdf5 related.
> Copy group attributes, fixes #838

- lstchain/io/io.py
For the case of giving a path instead of an `pytables.File`, the context manager would have already closed the file
> Fix indentation in add_source_files

- docs/lstchain_api/analysis/index.rst
- docs/lstchain_api/calib/index.rst
- docs/lstchain_api/datachecks/index.rst
- docs/lstchain_api/image/index.rst
- docs/lstchain_api/io/index.rst
- docs/lstchain_api/irf/index.rst
- docs/lstchain_api/mc/index.rst
- docs/lstchain_api/reco/index.rst
- docs/lstchain_api/scripts/index.rst
- docs/lstchain_api/tools/index.rst
- docs/lstchain_api/visualization/index.rst
- lstchain/analysis/post_dl2.py
- lstchain/datachecks/containers.py
- lstchain/datachecks/dl1_checker.py
- lstchain/scripts/lstchain_add_source_dependent_parameters.py
- lstchain/scripts/lstchain_check_dl1.py
- lstchain/scripts/lstchain_dl1_muon_analysis.py
- lstchain/scripts/lstchain_mc_r0_to_dl1.py
- lstchain/scripts/lstchain_mc_r0_to_dl2.py
- lstchain/scripts/lstchain_mc_rfperformance.py
- lstchain/scripts/lstchain_mc_sensitivity.py
- lstchain/scripts/lstchain_mc_trainpipe.py
- lstchain/scripts/lstchain_merge_muon_files.py
- lstchain/scripts/lstchain_tune_nsb.py
* Move to `automodapi` instead of `automodule`
* Add missing scripts documentation
* Modify datachecks docstrings for them to properly appear in the documentation
> Docs improvement

- environment.yml
- setup.py
We don't rely on pytest-runner and pytest-ordering anymore and pandas and seaborn were missing from the conda env, resulting in these packages being installed from pypi when setting up the env.
> Update requirements in setup.py and environment.yml

- lstchain/io/io.py
- lstchain/scripts/lstchain_dl1ab.py
The warnings were created by the astropy meta data tables, which we have no control over, so a warning is just annoying.
> Exit early if output file already exists and filter out NaturalNameWarnings

- lstchain/datachecks/dl1_checker.py
As reported by @morcuended, it is possible that there are `files_with_rings` but none of them contain good rings, which throws an error in [this line](https://github.com/cta-observatory/cta-lstchain/blob/046423a5454f79457eb05a1e6763ad3f0b1cd8c4/lstchain/datachecks/dl1_checker.py#L877). A solution would be to write the Muon error page if we have no `good_files`
> Change condition for muon error in datacheck

- .github/workflows/ci.yml
- environment.yml
- lstchain/calib/camera/calibration_calculator.py
- lstchain/calib/camera/flatfield.py
- lstchain/calib/camera/pedestals.py
- lstchain/io/io.py
- lstchain/io/tests/test_io.py
- lstchain/reco/r0_to_dl1.py
- lstchain/scripts/lstchain_dl1_muon_analysis.py
- lstchain/scripts/tests/test_lstchain_scripts.py
- lstchain/tools/lstchain_create_dl3_index_files.py
- lstchain/tools/lstchain_create_irf_files.py
- lstchain/tools/lstchain_fit_intensity_scan.py
- lstchain/visualization/plot_calib.py
- setup.py
Needs a new release of ctapipe_io_lst, until that is done, this is in draft mode.
It seems changes are again not large, so me might want to update already.
> Update ctapipe to 0.12.0, gammapy 0.19, pyirf 0.6

- lstchain/calib/camera/calibration_calculator.py
- lstchain/calib/camera/flatfield.py
- lstchain/calib/camera/pedestals.py
- lstchain/data/lstchain_standard_config.json
- lstchain/image/modifier.py
- lstchain/reco/r0_to_dl1.py
- lstchain/scripts/lstchain_data_r0_to_dl1.py
Cherry-picked the three important commits from #892 and added a fixed for the tune nsb configuration.
From the original PR:
> The config was not successfully read but the Components, therefore the interleaved events were processed with default trailet values (e.g. charge integration over only 7 samples, which explains the difference on the number of pe with respect to the beginning of night calibration). Also the f-factor systematic correction trailet was not included in the config file
>  Correct config of interleaved event processing

- lstchain/io/__init__.py
- lstchain/io/io.py
- lstchain/reco/dl1_to_dl2.py
- lstchain/scripts/lstchain_dl1_to_dl2.py
continued from #704 
This PR makes it possible to add source-dependent parameters during the RF training or DL1_to_dl2 process, so no need to add these parameters by another script explicitly.
> Add source-dependent parameters during RF training or dl1_to_dl2 process

- lstchain/io/data_management.py
- lstchain/scripts/lstchain_dl1ab.py
- lstchain/scripts/lstchain_mc_r0_to_dl2.py
- lstchain/scripts/lstchain_mc_rfperformance.py
- lstchain/scripts/lstchain_mc_trainpipe.py
- lstchain/scripts/lstchain_merge_hdf5_files.py
- lstchain/scripts/tests/test_lstchain_scripts.py
* Remove strtobool from distutils,
use action='store_true', action='store_false' instead.
* Changes default of pedestal cleaning in dl1ab to true, use
`--no-pedestal-cleaning` to disable
> Refactor command line arguments of scripts

- lstchain/conftest.py
- lstchain/io/__init__.py
- lstchain/io/config.py
- lstchain/io/tests/test_config.py
- lstchain/reco/dl1_to_dl2.py
- lstchain/scripts/tests/test_lstchain_scripts.py
- lstchain/tests/test_lstchain.py
This PR implemented pytest codes for source-dependent analysis (MC and real data).
I'd like to implement it before #875 , then I can also add additional pytest for source-dependent DL3 production.
> Add pytest for source-dependent analysis

- environment.yml
- setup.py
Contains the fix to the case for ext devices (TIB / UCTS) failing mid of a subrun
> Update ctapipe_io_lst requirement to 0.15.0

- lstchain/scripts/lstchain_longterm_dl1_check.py
From v0.8 onwards, due to some fixes, calibrated charges of real data are 2% smaller. Here we adapt some limits of the DL1 data check.
> Adapt charge limits to -2% change in calibration

- lstchain/scripts/lstchain_longterm_dl1_check.py
Fixed wrong range of RA and telescope azimuth in datacheck plots (was -pi, pi, now is 0, 2pi)
> Fix azimuth & RA range

- lstchain/scripts/lstchain_longterm_dl1_check.py
Previous version assigned to all runs in a night the value corresponding to the last run of the night.
> Fix run-wise mean of # of star-affected pixels

- lstchain/scripts/lstchain_dl1ab.py
I am not sure to understand why we don't want to write the images in this case?
But at least the docstring could mention it.
Condition at line 121 is useless.
> Clarify docstring for no-image in dl1a

- lstchain/scripts/lstchain_dl1_to_dl2.py
If the string `dl1` appears more than once on the dl2 filename, all occurrences will be replaced.
For example, in a file named `dl1_electron_20deg_180deg_dl1ab_tune_MC_to_Crab_testing.h5` both `dl1` strings will be replaced.
Another option could be using a regular expression, but I think this solution is much easier and straight forward
> replace only first occurrence on dl2 output filename

- lstchain/data/lstchain_standard_config.json
I think we always process LST1 alone with the "new" MC, so that should be standard.
> Allow only LST1 in standard config

- lstchain/data/lstchain_src_dep_config.json
- lstchain/io/tests/test_config.py
- lstchain/scripts/tests/test_lstchain_scripts.py
This PR is just an update of the source-dependent configuration file following the latest update of the standard one.
I also changed the default `n_off_wobble` to `1` from `3`.
> Update of a source-dependent config file

- lstchain/datachecks/dl1_checker.py
Now the lack of interleaved pedestal or flatfield events in the first subrun no longer implies that the corresponding type of events is ignored in the rest of the subruns.
> Improve DL1 check treatment of problematic data

- lstchain/tools/lstchain_create_calibration_file.py
At present we subtract the sim_tel calibration pedestals (pixel per pixel) in order to obtain the uncalibrated R1 with baseline = 0 but the sim_tel calibration pedestals are affected by sim_tel calibration errors (supposed errors on the calibration values) that are then propagated to the waveform. In this PR the camera median pedestals are subtracted instead, which are around the orginal pedestal shift,  since the calibration errors are gaussian. In future releases, we could think to use the meta sim_tel information to directly subtracted the shift
> Correct the R0 baseline subtraction in case of simulation events

- lstchain/reco/dl1_to_dl2.py
- lstchain/tests/test_lstchain.py
- notebooks/rf-performance.ipynb
We don't use any compression for the RF dump on disk.
I picked `compress=3` from a quick study (see below) that seems to give a good compromise: `1.2s --> 12.1s` to dump, `1.5-->3.8s` to read, `788MB-->179MB` on disk
Study:
```
In [13]: for i in range(9):
...:     print(i)
...:     %time joblib.dump(disp_sign,f'disp_sign_{i}.sav', compress=i)
...: 
0
CPU times: user 339 ms, sys: 890 ms, total: 1.23 s
Wall time: 1.41 s
1
CPU times: user 8.62 s, sys: 967 ms, total: 9.58 s
Wall time: 9.59 s
2
CPU times: user 9.11 s, sys: 599 ms, total: 9.71 s
Wall time: 9.72 s
3
CPU times: user 11.6 s, sys: 530 ms, total: 12.1 s
Wall time: 12.1 s
4
CPU times: user 12.7 s, sys: 504 ms, total: 13.2 s
Wall time: 13.2 s
5
CPU times: user 16.8 s, sys: 469 ms, total: 17.3 s
Wall time: 17.3 s
6
CPU times: user 28 …
```
> set joblib compress to 3

- docs/conf.py
- lstchain/data/lstchain_standard_config.json
- lstchain/high_level/significance_calculation.py
- lstchain/io/config.py
- lstchain/reco/dl1_to_dl2.py
- lstchain/reco/tests/test_utils.py
- lstchain/reco/utils.py
- lstchain/tests/test_lstchain.py
- setup.py
Early review is welcome
Fixes #948
> Allow selecting N samples for training and testing

- docs/examples/dl3_tool_config.json
- docs/examples/irf_tool_config.json
- lstchain/io/event_selection.py
- lstchain/io/tests/test_eventselection.py
- lstchain/tools/lstchain_create_irf_files.py
Makes the following new traits - 
- `min_event_p_en_bin`: minimum number of events to check, in each energy bin. I have changed the default value to 100, instead of the earlier 10, which was too low to be meaningful with the standard bins we provide. Needs to be fixed after some more tests.
- `min/max_gh/theta_cut`: Minimum and maximum cut values of gh_score (gammaness) and theta, while evaluating the percentile cuts.
- `fill_theta_cut`: Fill value of theta cut, when the number of events is below the minimum value, in each energy bin. For gh_score cut, I use the maximum value of 1, as it is fixed.
Also fixes the issue of #954 here to be more consistent PR, rather than #943. #942 can also follow this new change.
The example configs have been updated accordingly.
This will also help in …
> Remove hard-coded arguments in the energy-dependent cuts functions

- .github/workflows/ci.yml
@chaimain reported a strange error with mamba in the CI.
Switch to using the `setup-miniconda` github action to see if that works better (as we did recently for ctapipe)
> Use setup-miniconda in CI

- lstchain/data/lstchain_standard_config.json
- lstchain/tools/tests/test_tools.py
Based on https://indico.cta-observatory.org/event/3992/
and cross-check on real-data from @SeiyaNozaki showing no diff in Crab spectra between the two configs.
> Reduce size of random forests in standard config

- lstchain/io/io.py
- lstchain/io/tests/test_io.py
- lstchain/tools/lstchain_create_irf_files.py
continued from https://github.com/cta-observatory/cta-lstchain/pull/962
I implemented a new function to check mc_type (`point_like`, `diffuse`, `ring_wobble`) based on the suggestion in https://github.com/cta-observatory/pyirf/issues/176
This PR makes it possible to generate point-like IRF with ring-wobble MC properly (especially for source-dependent analysis).
> Add new function to check mc type

- docs/examples/dl3_tool_config.json
- docs/examples/irf_tool_config.json
- lstchain/data/lstchain_src_dep_config.json
- lstchain/io/event_selection.py
- lstchain/io/tests/test_eventselection.py
- lstchain/tools/lstchain_create_dl3_file.py
- lstchain/tools/lstchain_create_irf_files.py
- lstchain/tools/tests/test_tools.py
This PR implements energy-dependent alpha cut for the IRF/DL3 production.
The same solution as energy-dependent g/h cuts is basically used for the energy-dependent alpha cut.
(create a separate temporary header to save energy-dependent alpha cuts in IRF)
Since the alpha cut is already applied to observational DL3 data, there is no need to modify gammapy.
> DL3 energy-dependent alpha cut

- docs/examples/irf_tool_config.json
- lstchain/io/event_selection.py
Resolves #729 and also adds support for binning different MC nodes, with varying true energy range, into IRFs. Will be also useful for #711.
If there any other defaults to be modified, please let me know here.
> Update the event binning for true/reco energy and source offset

- lstchain/image/modifier.py
Correct a comment reflecting the implementation of the code before a correction (commit [ddff326](https://github.com/cta-observatory/cta-lstchain/pull/821/commits/ddff326554619dbf26cd437f26ad2790263e0215)) and currently wrong.
> Corrected missleading comment from previous code version

- lstchain/data/lstchain_dl1ab_tune_MC_to_Crab_config.json
- lstchain/data/lstchain_mc_config.json
- lstchain/data/lstchain_src_dep_config.json
- lstchain/data/lstchain_standard_config.json
- lstchain/io/config.py
- lstchain/io/tests/test_config.py
- lstchain/scripts/lstchain_dump_config.py
- lstchain/scripts/lstchain_tune_nsb.py
I think this should solve #924 (implementing solution B discussed there) #208 and improve the way we deal with configs.
- MC now gets its own config file so we stop forgetting about `apply_integration_correction`
- Users can still work with a limited config file (e.g. containing only an updated `tailcut` config different from the standard one)
- Users can then use the `--update-with` to dump a full configuration from that limited config
@SeiyaNozaki could you have a look at the update srcdep config please?
Fixes #924 
Fixes #208
> Dealing with configs in a better way

- lstchain/reco/dl1_to_dl2.py
- lstchain/scripts/lstchain_dl1_to_dl2.py
- lstchain/scripts/lstchain_mc_rfperformance.py
- lstchain/tests/test_lstchain.py
To solve #979 and reduce the memory usage during training and usage of random forest.
> Single RF loading at training and dl1->dl2

- lstchain/calib/camera/flatfield.py
- lstchain/calib/camera/pedestals.py
This code was comparing an astropy `TimeDelta` object to a plain number,
which was supposed to be in seconds. However, astropy treats plain
numbers as days, not seconds. Since astropy 5.1, this creates a warning
and made me find this bug. See
astropy/astropy#12887.
This means that in when calculating calibration coefficients, the condition for the sample duration was never met, only the number of events condition was used effectively.
I don't know if that has any consequences, since we right now analyze subrun by subrun and these are shorter than the  default 60s sample duration value.
> Fix comparison of timestamps in calibration code

- lstchain/io/event_selection.py
- lstchain/io/tests/test_eventselection.py
I think a greater *or equal* operator is actually what we want here. For example, if a user requests an efficiency of 100%, I think he expects all events to be included, which is not the case atm.
> greater or equal filters in DL3Cuts

- lstchain/tools/lstchain_create_irf_files.py
The latest version of gammapy (>0.20.1) always requires `RAD_MAX` to extract the ON/OFF region (e.g. `WobbleRegionsFinder`). This PR adds "dummy" RAD_MAX to adapt to the latest gammapy codes for source-dependent analysis.
> Add dummy RAD_MAX for source-dependent analysis

- lstchain/image/modifier.py
Unnecessary square root was added so the noise in dim pixels was defined as standard deviation. While later on it is used as a number of NSB photons from which poissonian number is selected (that adds this square root in the noise). Noise in the brigth pixels was properly defined (without square root)
> fixed calculation of noise in dim pixels parameter

- lstchain/data/lstchain_dl1ab_tune_MC_to_Crab_config.json
NSB parameters are obtained with the fixed code for finding the NSB-tuning parameters (#1024).  Note: the replaced parameters were very outdated, not obtained with the immediately earlier version, and were not those used for Crab in the analyses over the past few months.
Also switched off obsolete optical PSF tuning.
> Set correct NSB tuning settings for low-zenith MC

- lstchain/scripts/lstchain_dl1ab.py
Fixes #1032 
That is the simplest solution at the moment, the alternative being to revert entirely the `sin_az_tel` addition.
> checking if parameters exist before trying to update them

- lstchain/scripts/lstchain_data_r0_to_dl1.py
- lstchain/scripts/onsite/onsite_create_calibration_file.py
- lstchain/scripts/onsite/onsite_create_calibration_files_with_batch.py
- lstchain/scripts/onsite/onsite_create_drs4_pedestal_file.py
- lstchain/scripts/onsite/onsite_create_drs4_time_file.py
- lstchain/scripts/onsite/onsite_create_ffactor_systematics_file.py
> Allow passing of options to Tools in onsite scripts, fix flatfield overriding config

- lstchain/scripts/lstchain_dl1ab.py
I suppose the intent was to have these optional, since a default value was defined.
However, the reading from the config was mandatory, which is a contradiction.
This PR fixes this.
> truly optional config image_modifier

- lstchain/tools/lstchain_create_dl3_index_files.py
> Add another example message to index DL3 files

- lstchain/calib/camera/pedestals.py
- lstchain/scripts/onsite/onsite_create_calibration_files_with_batch.py
- lstchain/visualization/plot_calib.py
Urgent PR to fix a bug that makes all pixels tagged as outliers. I am afraid that this will ask a new release for the onsite installation
> Calibration bug fixes

- lstchain/scripts/onsite/onsite_create_calibration_file.py
On December 5th there was a change of the Mongo DB filter wheel names.
This PR should solve the present  problem to access the filter wheel number with the calibration script.
In order to have it active onsite, one should create a new release
However, **notice that** the change was corrupted till the 21st of December, so if no correction of the DB will be performed, the period from 5/12/2022 till 21/12/2022 will remain without automatic access to the filter wheel number
> URGENT: Add change of filter wheels' name in Mongo DB

- .github/workflows/ci.yml
CI is currently failing. The problem is related to conda installation with `conda-incubator/setup-miniconda@v2`. Same happened in ctapipe (see https://github.com/cta-observatory/ctapipe/pull/2207). I also updated version of checkout and python setup actions
> Change conda installation to mamba setup in CI workflow

- lstchain/scripts/lstchain_longterm_dl1_check.py
std dev of pedestal charge was displayed twice, instead of mean, std dev
> Fix duplicated quantity in DL1 check

- docs/conf.py
- docs/lst_analysis_workflow.rst
@chaimain realized that config files links were broken. here is a fix.
> fix missing configs in docs

- lstchain/data/normalised_pulse_template.py
closes #1058 
This was tested on current test files temporary using telescopes [1, 6] instead of [1, 2] in the failing test since LST2-4 are in the current file.
Failure behaviour in #1058 was observed before the fix.
> Add support for single gain telescope to the pulse template from eventsource

- lstchain/tools/lstchain_create_drs4_pedestal_file.py
Fixes #1014 
Adds a `--no-timelapse-correction` flag to the tool to disable the dt correction
@SeiyaNozaki
> Add alias to disable timelapse correction to lstchain_create_drs4_pedestal_file

- lstchain/high_level/interpolate.py
- lstchain/high_level/tests/test_interpolate.py
- lstchain/tools/tests/test_tools.py
A test on DL3 Tools when using IRF interpolation methods was failing as it required a list of IRFs which are not present as fixtures for the scope of the test session. These IRFs are created and tested in `lstchain/high_level/tests/test_interpolate` (through some "lengthy" code) for almost all combinations of IRF interpolations. 
As such, it is not essential to have separate and similar tests on DL3 Tools, for testing the same functionality.
This was missed in the earlier PR #711 as I tested in sequential order instead of in parallel (as done in CI).
In case, we require to have the DL3 Tools tested for the full functionality again, we would just need to shift ~150 lines of code from `lstchain/high_level/tests/test_interpolate.py` to `lstchain/conftest.py`
> Fix a failing test on DL3 Tool

- lstchain/reco/dl1_to_dl2.py
In this PR, I added exceptions for source-dependent analysis with real data when some required parameters (`source_name` or `source_ra` & `source_dec`, `observation_mode`) are not defined in a configuration file. It helps analyzers to understand the cause of the error when those parameters are missing.
> Add exceptions when required params are not defined for source-dep analysis

- docs/conf.py
- docs/snippets.rst
I also changed the link to ctapipe documentation to readthedocs link (for intersphinx mapping) and add some py class references from ctapipe to nitpick ignore list to avoid showing so many warnings that were preventing automatic deployment of the documentation.
follow-up of #1086
> Add code snippet to documentation to show how to print config and calibration files used in the analysis

- lstchain/conftest.py
- lstchain/scripts/lstchain_dvr_pixselector.py
- lstchain/scripts/tests/test_lstchain_scripts.py
This scripts uses DL1 files to identify (event-wise) pixels likely containing a signal, and creates hdf5 files with this information for use in the raw data volume reduction.
~~There are no tests for this script as of now, it requires to have DL1 files with the DL1a images. Are they produced? At the end of the tests the created DL1 files only have DL1b.~~
> Dvr pixel selector

- lstchain/high_level/interpolate.py
- lstchain/high_level/tests/test_interpolate.py
- lstchain/tools/lstchain_create_irf_files.py
Update IRF interpolation methods with the updated functionality from pyirf v0.8.1, and more specifically,
- Update the interpolation method of `GH_CUTS`, similar to `interpolate_rad_max` function of pyirf, 
- add a temp fix of `nan_to_num` on creating Effective Area (missing in pyirf) to avoid having `astropy's Masked` values for `EFFAREA` data
- update interpolation tests to work on the interpolation parameters of the fixtured MC test data sample and not on hard-coded values.
> Update IRF interpolation methods with pyirf v0.8.1

- lstchain/reco/utils.py
To calculate the elapsed time, a cut of `time_diff`<0.1 s is applied to exclude events suffered from DAQ break. However, such kind of filter is not applied to calculate the average of `delta_t` for the estimation of the trigger rate.
For example, when we have 'break' because of DAQ problem like below, the estimated trigger rate is 4.8 kHz, but the updated codes (excluding large `delta_t` events) estimate 7.4 kHz.
Here I set 0.01 s (100 Hz) as the limit for both elapsed/effective time calculation for the moment. Any comments are welcome.
> Update effective time calculation for observations suffered from busy stuck problem

- lstchain/data/normalised_pulse_template.py
- lstchain/data/tests/test_normalised_pulse_template.py
- lstchain/image/modifier.py
- lstchain/reco/r0_to_dl1.py
- lstchain/reco/reconstructorCC.py
New version of #1006 done in a more recent version of lstchain (the diff ended up being the same, but it cleans up the commit history). Significantly accelerate NSB injection on waveforms compared to the current implementation using scipy.interpd1d every time.
> Use numba njit code to inject NSB in R1 waveforms

- docs/conf.py
- lstchain/reco/tests/test_utils.py
- lstchain/tools/tests/test_fit_intensity_scan.py
- scripts/create_test_calibration_files.sh
Forwarded from #1106 to have proper commit for the exact change. This will help solve some failing tests in #1054
> Fix tests for ctapipe_0.17 branch

- lstchain/data/lstchain_standard_config.json
- lstchain/image/tests/test_modifier.py
- lstchain/reco/r0_to_dl1.py
New commit for the code in PR [https://github.com/cta-observatory/cta-lstchain/pull/1072](https://github.com/cta-observatory/cta-lstchain/pull/1072) with correct rebase to ctapipe_0.17. It substitutes PR 1072
> PR for ctapipe 0.17 : write pedestal and ff events to a h5 files

- docs/lstchain_api/high_level/index.rst
- lstchain/high_level/__init__.py
- lstchain/high_level/interpolate.py
There was a missing `__all__` in `lstchain.high_level.interpolate` module leading to the failing `build docs` test in #1105 and #1054
> Fix failing docs test 

- .github/workflows/ci.yml
- environment.yml
- lstchain/data/lstchain_lhfit_config.json
- lstchain/data/lstchain_standard_config.json
- setup.cfg
- setup.py
There was a [gammapy release](https://github.com/gammapy/gammapy/releases/tag/v1.1) very recently and we can also follow the latest [ctapipe](https://github.com/cta-observatory/ctapipe/releases/tag/v0.19.2) one
> Update dependencies to current versions, add python 3.11 CI

- lstchain/scripts/lstchain_create_run_summary.py
The EVBv6 test files created an exception that was not handled, preventing the creating of the run summary.
I think it does not really make sense here to check for specific exceptions, anything we can't identify is probably not analyzable at the moment.
> Catch all exceptions in create_run_summary

- environment.yml
conda-forge recommends not mixing default packages with conda-forge packages.
> Remove default channel from conda env

- lstchain/scripts/lstchain_dvr_pixselector.py
Make lstchain_dvr_pixselector.py back-compatible with DL1 files containing obsolete instrument description: now the camera geometry is obtained from the LST event source.
Also: do not skip files in which no events are tagged as cosmics. In some files the tagging failed, and cosmics are actually tagged as "unknown" (whereas FF and pedestal are heuristically recognized in the DL1 file). We now assume those are cosmics.
> Make lstchain_dvr_pixselector.py back-compatible with v0.9 DL1

- environment.yml
- setup.py
The new `ctapipe_io_lst` version will allow to read EvB6 data
(tests will pass whenever [the new version of ctapipe_io_lst](https://github.com/cta-observatory/ctapipe_io_lst/releases/tag/v0.22.0) is uploaded to pypi
> Bump ctapipe_io_lst version

- lstchain/calib/camera/pixel_threshold_estimation.py
The former approach np.array(f.root[].cols.charge_mean) results in some cases  in an attempt to allocate a huge array (instead of just 2x2x1855), and hence a crash.  So far I only had this problem at PIC, using lstchain 0.9.13. No idea why...
With current main branch the same code works well at the IT cluster. 
Since the new lines work in both cases, I propose to merge the change.
> Change way to access monitoring info in dl1 file

- lstchain/scripts/lstchain_create_run_summary.py
Astropy Tables `.write` method avoids overwriting files unless it is specified as `overwrite=True`. This PR adds a `overwrite` command line argument to allow for overwriting summary files.
> Add option to overwite summary file

- lstchain/calib/camera/calibration_calculator.py
Add the detection QE dispersion  over the camera (~7%) to estimate the cuts for selecting pixels outliers on the base of the calculated number of pe by the F factor method. In a first step we neglected the ~6-7% dispersion, which is ok for the standard FF intensity but not for filters delivering to very high FF intensities (> 1000 pe/pixel). This ended up with many pixels wrongly set as outliers for the last high intensity points of the filter scan.
> Add detection QE spread for outlier estimation

- lstchain/calib/camera/flatfield.py
- lstchain/data/onsite_camera_calibration_param.json
- lstchain/scripts/onsite/onsite_create_calibration_file.py
- lstchain/tools/lstchain_create_calibration_file.py
This PR add the option to read more than a sub_run file if necessary and improves the calibration out messages. In particular, add a warning in case there is not enough events statistics in the run (as it happened for run 13653)
> Improve calibration "info" and "warning" messages 

- lstchain/reco/dl1_to_dl2.py
- lstchain/scripts/lstchain_dl1_to_dl2.py
Related to #1079 
This PR normalize `az_tel` values to the range of [0, 360) degrees which is same as the distribution of MC data points. In addition, if there is no `sin_az_tel` in DL1 file because the DL1 was created using former version of lstchain, it computes `sin_az_tel` in dl1_to_dl2 step.
> Normalize `az_tel` to the range of [0, 360) and compute sin_az_tel in dl1_to_dl2 step

- lstchain/calib/camera/calibration_calculator.py
- lstchain/data/catB_camera_calibration_param.json
I recently [(PR 1142)](https://github.com/cta-observatory/cta-lstchain/pull/1142) changed the value in the json file equal to the default hg_lg_ratio trailet value (17.4), but that is correct  in the case of not calibrated data,  we instead recalibrate directly already calibrated data, so the correct ratio is supposed to be 1 as it was indeed in the json file (probably time to go on holidays ...).
> Patch PR: change default hg_lg_ratio

- lstchain/calib/camera/calibration_calculator.py
- lstchain/reco/r0_to_dl1.py
> Fix unusable pixels usage in muon analysis

- lstchain/tools/lstchain_fit_intensity_scan.py
Fix necessary due to changes in PR [https://github.com/cta-observatory/cta-lstchain/pull/1149](https://github.com/cta-observatory/cta-lstchain/pull/1149)
> Fix treatment of Nan values in filter scan fit

- lstchain/scripts/tests/test_lstchain_scripts.py
Test files for 2006 runs were updated, so run type identified by run summary script changed from ERROR to PEDCALIB
> Updated run_type in summary test

- setup.py
> Pin matplotlib to 3.7.0 to avoid setting deprecated seaborn styles in matplotlib 3.8

- README.md
Previous ctapipe docs links in the README were pointing to GH pages instead of the current RTD.
> Update links to ctapipe docs in README

- environment.yml
- setup.py
> request ctaplot 0.6.4 to fix the seaborn style issue

- .github/workflows/ci.yml
Last time it was deployed to GH pages was 3 months ago. I think it is because of the branch naming.
> Change master to main to trigger docs deployment

- lstchain/tools/lstchain_create_irf_files.py
> Properly normalize edisp in lstchain v0.9

- lstchain/scripts/lstchain_create_run_summary.py
- setup.py
Counters are not used in case of CTA R1 input, so just don't compute them.
We rely on the `event_time_s`, `event_time_qns` and the `event_type` reported by EVB for this.
> Make run_summary script work with ctar1 data, store format string

- lstchain/image/modifier.py
Just unse nanmedian, nanstd to skip non-existent pixels
> Deal with missing modules in modifier.py

- docs/examples/dl3_tool_config.json
- docs/examples/irf_tool_config.json
Also, I still find it confusing that these config files are not in lstchain/data, together with the rest of lstchain config files.
Shouldn't they be placed in the same location?
Moreover, these example config files are not included in the package data in `setup.py`:
```
package_data={
'lstchain': [
'data/*',
'resources/*',
],
},
```
> Set minimum intensity by default to 50 p.e. in example DL3 and IRF configs

- lstchain/high_level/hdu_table.py
- lstchain/tools/lstchain_create_dl3_file.py
There are two small updates in this PR.
1. Sort DL3 file based on event_id after stacking data frame for each assumed source position (on, off_180 etc), just not to confuse analyzers
2. Use the same reco position (derived from the first event) for all events. The reconstructed position fields were filled with the assumed source positions (ON and OFF) for each event. ON and OFF positions were selected based on the camera frame with respect to the source position on the camera. So the assumed OFF positions in ICRS frame differed for each event in principle. But, sometimes not all OFF events are extracted for higher analysis (gammapy) mostly with pre-defined region cut (0.1 degrees, stored in the header) mostly because of the telescope tracking condition. This PR solves such issue.
> Small update source-dependent DL3 step

- notebooks/explore_DL2.ipynb
Make explore_DL2 notebook faster and less memory-hungry by keeping only relevant variables and ignoring from the start very low gammaness events
> Make explore_DL2 notebook faster and less memory-hungry

- lstchain/scripts/lstchain_dvr_pixselector.py
Fixed long-standing BUG which made that the info in the DVR_settings file produced by the script contained only the information of the last subrun.
Improvements in logging
Now by default only 10 files (subruns) of the input set, distributed uniformly along the run, are actually processed to determine the DVR settings. This is to speed up the process (since the settings are determined for the whole run, we do not need to check all subruns).
> Fixed bug & couple of improvements in lstchain_dvr_pixselector

- lstchain/reco/dl1_to_dl2.py
- lstchain/scripts/lstchain_dl1_to_dl2.py
This PR updates the dl1 to dl2 step:
- Load each random forest model just before using it. Now the script loads all models at the beginning of the script and it consumes much memory. Just pass the model path to `apply_models`. This option was already implemented in `apply_models`, but not used for the script before.
- This script applies the particle classification models to the data twice for `gammaness` and `reco_type`. But `reco_type` can be set based on `gammaness` as suggested by @maxnoe here. Even, we can remove `reco_type` which will not be used for the analysis.
https://github.com/cta-observatory/cta-lstchain/pull/1077#discussion_r1104715136
> Update dl1 to dl2 script (Less required memory and less required step)

- .github/workflows/ci.yml
- environment.yml
- lstchain/scripts/lstchain_create_run_summary.py
- lstchain/tools/lstchain_create_drs4_pedestal_file.py
- setup.py
This updates to ctapipe_io_lst, which includes the parsing of the EVB preprocessing steps.
This is also stored into the runsummary.
To not completely dominate the run summary with the string representation, I put the integer value and only for MONO events.
Here is how you can get something more human readable from that:
```
In [1]: from ctapipe_io_lst.evb_preprocessing import EVBPreprocessingFlag
In [2]: EVBPreprocessingFlag(103)
Out[2]: <EVBPreprocessingFlag.GAIN_SELECTION|BASELINE_SUBTRACTION|DELTA_T_CORRECTION|PEDESTAL_SUBTRACTION|PE_CALIBRATION: 103>
In [3]: EVBPreprocessingFlag(3)
Out[3]: <EVBPreprocessingFlag.GAIN_SELECTION|BASELINE_SUBTRACTION: 3>
In [4]: EVBPreprocessingFlag(2)
Out[4]: <EVBPreprocessingFlag.BASELINE_SUBTRACTION: 2>
```
> Require ctapipe_io_lst 0.23, add evb preprocessing to run summary

- lstchain/scripts/lstchain_dvr_pixselector.py
When used for determining the settings for the Data Volume Reduction (DVR) of a given run, the program now outputs also a .json file (adapted to the NSB conditions) for use in the lstchain_dl1ab step
> Compute cleaning thresholds in lstchain_dvr_pixselector

- lstchain/reco/dl1_to_dl2.py
Update of the build_models method to ensure more effectively that non-finite values in features are removed.
Main change : additional call to utils.filter_events before the classifier training to account for the new 'signed_time_gradient'. Other new parameters that may be  affected include the 'signed skewness', reconstructed energy and reconstructed disp.
I also moved the 'sin_az_tel' computation before the first call to utils.filter_events. I have never seen a case when 'az_tel' is not finite but this would handle it.
Dedicated tests could be added in a LHfit related PR since this is where a failure case was observed.
closes #1206
> Improve non-finite parameters rejection when training models

- lstchain/data/lstchain_lhfit_config.json
- lstchain/reco/r0_to_dl1.py
- lstchain/reco/reconstructor.py
- lstchain/tests/test_lstchain.py
Two elements implemented for (MC) processing : 
- DVR based pixel selection for both data and MC before performing the likelihood fit. This is a small change to the pixels selected for data after volume reduction, but it allows to have the same selection in MC.
- A new method to extract the pedestal variance in MC : extract once at the start (like it is done for data using interleaved events). This is required to keep events where the full camera is selected and to avoid bias in the extraction in the case of dvr pixel selection
Draft to extend test coverage
> LHfit : DVR based pixel selection + new ped variance extraction for MC

- lstchain/io/lstcontainers.py
It seems the help string of the definition of `concentraion_cog` was not updated after cta-observatory/ctapipe#1572 (almost 3 years ago)
> Update help string of the definition of concentration_cog

- lstchain/scripts/lstchain_dl1_to_dl2.py
This PR solves the operand type error when raising an error because the output file already exists.
> Fix unsupported operand type in existing DL2 file

- lstchain/onsite.py
- lstchain/scripts/onsite/onsite_create_cat_B_calibration_file.py
- lstchain/scripts/onsite/onsite_create_cat_B_calibration_files_with_batch.py
The present official tree path for DL1 files contains also the "short" code version: E.g.
`/fefs/aswg/data/real/DL1/[date]/v0.10`
This was not considered in the  interleaved  search function, this PR correct the search.
> Correct the search of interleaved files in the official tree

- lstchain/scripts/lstchain_r0_to_r0g.py
Program crashed if no FF-like events were found - one log message had the total number in the denominator of a fraction.
> Avoid crash in log message if no FF events were found

- notebooks/data_quality.ipynb
Previous example was misleading, since it included only files processed with v0.10, rather than all available files
> Better example of input set of files. 

- lstchain/scripts/lstchain_dvr_pixselector.py
Added missing "dynamic_cleaning" setting to the json files produced with suggested cleaning levels
> Cleaning config from lstchain_dvr_pixselector.py

- lstchain/scripts/tests/test_lstchain_scripts.py
Bug #1266 went unnoticed because the script was not covered by tests. Adding a basic test that runs the script.
> Add test for nsb waveform tuning script

- lstchain/data/lstchain_standard_config.json
- lstchain/reco/dl1_to_dl2.py
- lstchain/reco/tests/test_utils.py
- lstchain/reco/utils.py
This is to avoid jumps in RF performance in the "mid-points" between training pointing nodes, just because the event statistics occasionally have jumps between neighboring nodes. 
The idea is to  use "sample_weight", i.e. a weight for each event in the training set, calculated such that each of the pointing nodes has the same total weight.
The calculation is done with all events that are passed to the RFs.  Of course, the energy (and impact) range of those events between culmination and high zenith change a lot, so "same number of events" does not mean much when comparing such extremes, but the point here is to avoid steps between _neighboring_ bins (and for those, indeed, the numbers of events are comparable quantities). Only if the impact and energy ranges were poorly chosen (and …
> Computation of pointing-dependent weights for MC events 

- README.md
- Removed the conda installation link
- Fixed some typos and language stuff
> Update links conda in README.md

- lstchain/high_level/interpolate.py
- lstchain/high_level/tests/test_interpolate.py
> Fix the shape of the interpolated Effective Area

- lstchain/io/io.py
- lstchain/io/tests/test_io.py
- lstchain/reco/r0_to_dl1.py
closes #1271 
Change the behaviour of `extract_simulation_nsb` to identify the nsb entries used with the telescopes and ignore other entries (for prod5 and LSTprod2). Return a dictionary to be accessed by tel_id.
Replace the access to simtel object by hand in favour of `SimTelFile.history`.
> Fix original MC nsb reading

- lstchain/tools/tests/test_tools.py
> Fix a small test to avoid random fails

- notebooks/data_quality.ipynb
This was not working for >1  different runs between the tables because of improper use of panda's "drop"
Fixes #1277
> Ensure consistency between the cis and runsummary tables

- lstchain/data/lstchain_lhfit_config.json
- lstchain/data/lstchain_standard_config.json
- lstchain/image/modifier.py
- lstchain/image/tests/test_modifier.py
- lstchain/io/io.py
- lstchain/io/tests/test_io.py
- lstchain/reco/r0_to_dl1.py
- lstchain/reco/reconstructor.py
- lstchain/tests/test_lstchain.py
In order to implement the possibility to pre-generate nsb waveforms to add nsb to events instead of generating new nsb waveforms on the fly, a new class was added.
The class `WaveformNsbTunner` take a new config file entry `pre_computed_multiplicity` which can be set to 0 to generate nsb on the fly. Or to any int to pre-generate `pre_computed_multiplicity` X number of pixels X number of gains waveforms.
Closes #1273 
To do before removing draft : 
Some processing duration to illustrate the gain on a single (proton) MC file : 
+50% NSB, no pre-generation : 1min 39s
+50% NSB, 10X pre-generation : 1min 28s
+1000% NSB, no pre-generation : 3min 18s
+1000% NSB, 10X pre-generation : 1min 31s
Results of the tuning are compatible between using pre-generated waveforms or on the fly generation. …
> NSB tunning : pre-generated NSB only waveforms and a new class 

- lstchain/data/lstchain_lhfit_config.json
- lstchain/data/lstchain_standard_config.json
- lstchain/image/modifier.py
- lstchain/image/tests/test_modifier.py
- lstchain/reco/r0_to_dl1.py
- lstchain/scripts/lstchain_tune_nsb_waveform.py
- lstchain/scripts/tests/test_lstchain_scripts.py
Code to compute the needed NSB tuning in the MC waveforms to match a certain data file.
It does not require to know the level of NSB simulated, or the level of electronic noise. It obtains the necessary noise addition in a purely empirical way.
> Waveform noise tuner

- .github/workflows/ci.yml
There seems to be a problem with the latest release. See https://github.com/mamba-org/setup-micromamba/issues/225
Remember to remove the pin whenever it is fixed at the mamba side.
> Pin micromamba 2.0.0-0 in GitHub Actions

- setup.py
Should not be needed anymore and fixes a dependabot alert
> Remove jinja pin

- lstchain/tools/tests/test_tools.py
This test was failing from now and then giving IndexErrors. Here I try to simplify the search for maxima of the EDISP PDF and avoid loops inside the test using pytest parametrization decorator that runs the test for every combination of scaling factor and true energy value.
See action job: https://github.com/cta-observatory/cta-lstchain/actions/runs/11127968103/job/30921574910?pr=1289
```python
order_max = []
order_max_mod = []
for idx, _ in enumerate(e_true_list):
for j in range(len(e_migra)):
if e_migra_prob[idx][j] > e_migra_prob[idx][j - 1]:
order_max.append(j)
if e_migra_prob_mod[idx][j] > e_migra_prob_mod[idx][j - 1]:
order_max_mod.append(j)
for i in range(len(order_max)):
>           assert order_max[i] != order_max_mod[i]
E           IndexError: list index out of range
```
> Simplify test for scaling true energy in IRFs and try to make it deterministic

- lstchain/tools/lstchain_create_irf_files.py
To avoid astropy warnings.
Fixes #1292
> Use hierarch card for HDU keywords longer than eight characters

- docs/conf.py
- lstchain/high_level/hdu_table.py
Addresses #1293 
So far the first event's pointing was used. This is problematic for runs in which the pointing is unstable at the beginning.
> Computing the run pointing in sky coordinates

- environment.yml
- setup.py
To be compatible with the new LST calibration library, we must require ctapipe_io_lst >= 0.24.0.
From 0.23 to 0.24 there was only the addition of ctapipe 0.21 compatibility as a major change
> Bump to ctapipe_io_lst 0.24

- lstchain/image/modifier.py
Avoid a lot of zombie processes when using these functions repeatedly
> Close EventSource instances

- .gitignore
- lstchain/reco/r0_to_dl1.py
- lstchain/scripts/lstchain_mc_r0_to_dl1.py
- lstchain/scripts/lstchain_mc_r0_to_dl2.py
- lstchain/scripts/tests/test_lstchain_scripts.py
- notebooks/disp.ipynb
- notebooks/example_container.ipynb
- notebooks/lstchain.ipynb
- notebooks/mc_energy_distr.ipynb
- notebooks/step_by_step_dl0_to_dl1.ipynb
New file is not yet on the data server, but will be there tomorrow
> Replace test file

- .github/workflows/ci.yml
- environment.yml
- lstchain/scripts/lstchain_r0_to_r0g.py
- lstchain/scripts/lstchain_r0g_to_r0v.py
- setup.cfg
- setup.py
This is intended to enable a more efficient lossless compression for R0G and R0V files
It uses protozfits 2.6.1. Since that version only supports python >= 3.10, we have had to raise lstchain's minimal requirement to python >=3.10
> Better R0g r0v compression, drop python 3.9

- lstchain/tools/lstchain_create_irf_files.py
This PR fix the issue https://github.com/cta-observatory/cta-lstchain/issues/1322 . The bloc of code managing the FoV binning as been moved too.
The PR also add a warning message if the FoV binning is wider than the simulated FoV, and restrict the gammas used for the computation of energy dependant cuts (gh and theta) to the ones within the FoV range considered for the IRF.
> Fix issue with FoV offset binnning when using energy dependant theta cut and diffuse MC

- lstchain/datachecks/dl1_checker.py
- lstchain/scripts/lstchain_check_dl1.py
It did not work when the "pdf" option was used with subrun-wise DL1 files as input (as opposed to subrun-wise datacheck files)
> Use provided muons directory

- lstchain/datachecks/dl1_checker.py
Keep in the attrs of the cosmics table of the dl1 datacheck files the configuration of the analysis.
We will need at least the cleaning levels to interpret the checks, since e.g. the intensity values depend on them
> Propagate config to datacheck files

- lstchain/scripts/lstchain_check_dl1.py
Just to get rid of messages
`No activity has been explicitly started, starting new default activity. Consider calling Provenance().start_activity(<name>) explicitly.`
which come from a call to load_camera_geometry()
> Clean lstchain_check_dl1.py logging

- lstchain/image/cleaning.py
- lstchain/scripts/lstchain_dvr_pixselector.py
- lstchain/scripts/lstchain_find_tailcuts.py
Find adequate cleaning levels (and MC NSB tuning settings) to process a given run, just based on the pixel charges extracted from interleaved pedestal events. See #1330 for some tests of performance.
> Tailcut finder function and script

- lstchain/data/lstchain_standard_config.json
- lstchain/reco/dl1_to_dl2.py
- lstchain/scripts/lstchain_dl1_to_dl2.py
This should solve the issue of RF "performance jumps" at high zenith angles, when the pointing goes through the middle points between training nodes. See #1317
**NOTE: this is a different implementation of the interpolation approach proposed by @gabemery, see branch https://github.com/cta-observatory/cta-lstchain/tree/dl2_RF_interpolate)**
If the interpolation option is activated we call the RF predictors twice, for each of the two closest MC training nodes, then interpolate (or extrapolate) the values to the actual telescope pointing for each event.
Currently the training sample pointings are obtained from the path to the training sample(provided via config file). A better solution would be to add to the .sav files an array with the zenith and azimuth values of the MC training nodes.
> Interpolation of RF predictions with cosZD, for homogeneous performance

- lstchain/scripts/lstchain_dl1ab.py
v0.9 and v0.10 DL1 files differ in that the latter have units for some of the columns, which are missing in the former. With this change we ensure that the DL1 parameters table has consistent units for all DL1ab outputs, regardless of whether the input file was v0.9 or v0.10
> Correct units in DL1ab output, when processing v0.9 files

- notebooks/plot_theta2_from_dl3.ipynb
Before, it defined the formula in the notebook and did not consider the negative excess case. It now uses the same function as the one in the `explore DL2` notebook to make the theta2 plots from DL2.
Some other minor cleanup (imports, comments)
> Use Li and Ma significance formula from pyirf for theta2 plot from DL3 notebook

- lstchain/scripts/lstchain_dl1ab.py
If an outdated Subarray info is found in input file, it is not propagated to the output. A new one is created and saved instead.
This makes that even for v0.9 DL1 input files, the output DL1 file contains v0.10-compliant Subarray info.
> Correct Subarray info in output DL1 files

- lstchain/scripts/lstchain_dl1ab.py
A solution to too bulky outputs of DL1ab, as proposed by @maxnoe
> Remove images from list of nodes to be copied

- lstchain/reco/r0_to_dl1.py
This solves occasional crashes of r0_to_dl1, when an event tagged as interleaved turns out to have no R0 waveform (i.e. it is gain selected and possibly volume-reduced)
> Require R0 waveform for interleaved events

- lstchain/reco/utils.py
The cut is based on the intensity spectrum (dR/dI) obtained from a DL2 table.
The idea is to use the cut as a "software threshold" which improves the agreement between data and MC by removing events too close to trigger threshold (whose configuration is fixed in MC but variable in data). 
The proposed intensity cut is just a fixed factor (1.3) above the intensity for which 50% of the peak rate (dR/dI) of the intensity spectrum is reached. The factor is chosen such that the bulk of the good-quality data taken in dark conditions (hence processed with 8-4 p.e. cleaning) have a cut around 50 p.e. 
50 p.e. is close to the peak of the intensity spectrum for such data, and hence will mostly remove the low-energy events close to threshold for which we may expect trigger-induced differences …
> Functions to obtain recommended intensity cut

- lstchain/reco/utils.py
Although interleaved pedestals and flatfield events should not be a nuisance around the peak of the intensity distribution for cosmics, it is better to make the histogram only with events tagged as cosmics.
> select cosmics for dR/dI spectrum

- lstchain/scripts/lstchain_r0g_to_r0v.py
Option to correct R0V files that were created correctly, except for the pixel status bits (see #1376)
This PR is to correct _already existing_ R0V files (whereas #1376 solves the original problem in the R0V production)
> Added command-line option to fix R0V files which lack pixel status info

- lstchain/scripts/lstchain_cherenkov_transparency.py
For example, for the day 20250823, in which several subruns of run 21523 had to be discarded, the cherenkov transparency script gives this error: 
```
Traceback (most recent call last):
File "/var/spool/slurm//job48183790/slurm_script", line 10, in <module>
sys.exit(main())
^^^^^^
File "/fefs/aswg/software/conda/envs/osa-v0.11.3/lib/python3.11/site-packages/lstchain/scripts/lstchain_cherenkov_transparency.py", line 218, in main
dummy[jj] = nn
~~~~~^^^^
IndexError: index 106 is out of bounds for axis 0 with size 83
/fefs/aswg/software/conda/envs/osa-v0.11.3/lib/python3.11/site-packages/tables/file.py:130: UnclosedFileWarning: Closing remaining open file: /fefs/onsite/data/lst-pipe/LSTN-01/DL1/20250823/v0.11/tailcut84/datacheck/datacheck_dl1_LST-1.Run21523.h5 …
```
> Using the subrun index gives an error in the cherenkov transparency script for days in which some subruns failed and were discarded
