cta-observatory/cta-lstchain

reco/LST1_Hillas.py, reco/PlotDisp.py, reco/RFDisp.py, reco/RFEnergy.py, reco/RFGHseparation.py
The HillasContainer replaces 'cen_x' with 'x', 'cen_y' with 'y' and 'size' with 'intensity'
=> Updated Hillas parameters to be compliant with new version of ctapipe.

reco/Disp.py
Changed one line in Disp.py to correct multiplication of rotation matrix.
=> correct coordinate rotation

lstchain/io/containers.py, lstchain/reco/dl0_to_dl1.py, lstchain/reco/reco_dl1_to_dl2.py, lstchain/reco/utils.py, lstchain/visualization/plot_dl2.py, scripts/lst-recopipe.py, scripts/lst-trainpipe.py, scripts/lstpipe.py
- some due to last PR and related to disp refactored in disp_
- scripts could not work if the result dir did not exist before
- models could not be loaded if the path didnt end with /
- bug do to refactoring of ApplyModels in number of arguments
- in lstpipe.py path_models arguments was not passed
- also removed `impact` features that was a duplication of `mc_core_distance`
- corrected bug due to renaming "w/l" as "wl"
I retested all scripts that are working now.
=> Correcting some bugs:

lstchain/reco/dl0_to_dl1.py
`hillas_parameters_2` has been removed from ctapipe
=> remove hillas_parameters_2

notebooks/Step_by_Step_dl0_to_dl1.ipynb
The notebook was not working due to some packages were not defined at the beginning. 
Also it would be nice to clarify: 
- the variable for unit conversion, is it MeVtoTeV? -> then the value has to be changed
- is it MeVtoGeV? -> then the name of the variable should be changed
I'm asking now because I see that the energies emax, emin... are given in TeV, if the energy of the events is also given in TeV, then it would be better to work on TeV. 
I did not have time yet to check if the absolute results of the weighting are ok, the spectral index, as @moralejo commented out, seems to be ok.
=> Small corrections to make the notebook work

scripts/lst-r0_to_dl1.py, scripts/merge_hdf5_files.py
Adding two simple scripts for the first part of the reconstruction:
- r0 to dl1
- merging hfd5 files (especially after r0 to dl1)
=> adding scripts for the r0 to dl1 reco part

lstchain/reco/utils.py, tests/test_lstchain.py
The calculation was actually wrong.
Also solves #91.
I added a unit test to check that this is now working as expected.
=> Fix wrong calculations in `cartesian_to_polar`

lstchain/reco/dl0_to_dl1.py, lstchain/reco/dl1_to_dl2.py, scripts/lst-recopipe.py, scripts/lst-rfperformance.py, tests/test_lstchain.py
Hi
This is a quick fix solving issue #89 
With this, all the tests will pass.
Then we can work on #92 
@misabelber if you want to implement a more versatile version following discussion in #89 after this, please do.
=> Quickfix pandas

environment.yml
Fix for https://github.com/cta-observatory/ctapipe_io_lst/issues/4
=> Add protozfitsreader

.travis.yml, README.md, lstchain/io/tests/test_lsteventsource.py
Hi
This is a working version of the travis configuration to build the ctapipe master for the repository.
It might not be the cleanest version, I would appreciate if @MaxNoe had a quick look and suggestions.
I also updated the README with corresponding installation procedure (and commented the old one for later reference).
For the tests to pass, I had to comment one on lsteventsource.
=> Travis for ctapipe master

lstchain/io/lstcontainers.py, lstchain/reco/dl0_to_dl1.py, lstchain/reco/dl1_to_dl2.py
I looked a bit at these bare excepts and think most of them hurt more than they help. 
Therefore here I propose to remove many of them and actually raise exceptions in case a function is called with wrong input.
=> Bare excepts

lstchain/calib/camera/calib.py, lstchain/calib/camera/flatfield.py, lstchain/calib/camera/pedestals.py, lstchain/io/lstcontainers.py, lstchain/reco/dl0_to_dl1.py, lstchain/tools/calc_flatfield.py, notebooks/Step_by_Step_dl0_to_dl1.ipynb
Trying to fix the charge integration.
Probably need review and help from @FrancaCassol
=> fixing charge integration with new API from ctapipe

lstchain/reco/dl0_to_dl1.py, scripts/muon_reconstruction.py
See https://github.com/cta-observatory/ctapipe/commit/b010cf6393f9bed387eb2ef818fc76c207520bce
=> Retire CameraR1Calibrator

README.md
The installation instructions are now in line with the installation done by Travis (and are much simpler).
=> Simplify install instruction in README

lstchain/reco/dl0_to_dl1.py, tests/test_lstchain.py
Fixing new ctapipe calibration API.
Also adding the registry download for astropy in tests while investigating further the issue.
=> fixing new ctapipe calibration API

lstchain/reco/utils.py
Following the suggestion from @MaxNoe (thanks) in PR #122 .
This will also solve the issue we have sometimes with getting the position of Roque de Los Muchachos from astropy servers.
The position is taken from Google Earth.
=> changing location to the exact LST1 position

lstchain/io/lstcontainers.py, lstchain/reco/dl0_to_dl1.py, lstchain/reco/dl1_to_dl2.py, lstchain/reco/utils.py, lstchain/visualization/plot_dl2.py, scripts/lst-recopipe.py, scripts/lst-rfperformance.py, scripts/lst-trainpipe.py
- create the dl1 container outside the event loop and then fill it -> improve speed.
- fill dl1_container with mc_type from `event.mc` info (from simtel info)
- do not compute parameters if image size = 0 after cleaning
- use `mc_type` and removes `hadroness`
=> Improvements in DL1 reconstruction

lstchain/mc/plot_utils.py, lstchain/mc/sensitivity.py
My bad, we merged too soon.
Here is a quick fix.
=> fix imports and references

lstchain/io/lstcontainers.py
Fixing bug appearing after ctapipe PR https://github.com/cta-observatory/ctapipe/pull/1079
=> fixing bug with unit concerning pulse_time

lstchain/calib/camera/calib.py, lstchain/calib/camera/tests/test_calib.py, lstchain/reco/dl0_to_dl1.py
=> Use new gain selector from ctapipe

lstchain/visualization/plot_dl2.py, lstchain/visualization/tests/test_plot_dl2.py
Fixing bug about `disp_rec` name in data and adding a unit test for `plot_disp`
Also made some pep8 fixes.
=> Fix bug plot_disp in vizualisation.plot_dl2

lstchain/calib/camera/__init__.py, lstchain/calib/camera/calib.py, lstchain/io/config.py, lstchain/mc/mc.py, lstchain/mc/plot_utils.py, lstchain/mc/sensitivity.py, lstchain/reco/__init__.py, lstchain/reco/dl1_to_dl2.py
Remove some unused imports and fixe wild imports
=> Fix modules imports

lstchain/reco/disp.py, lstchain/reco/utils.py
- `disp_to_pos` was actually not imported in `lstchain.reco.utils` but the functions were not unit tested
- added unit test for these
- improve doc
=> fixing an import error in disp and utils

lstchain/io/io.py, lstchain/io/tests/test_io.py, lstchain/reco/dl1_to_dl2.py, lstchain/tests/test_lstchain.py, scripts/lst-recopipe.py, scripts/lst-rfperformance.py
- Improve consistency across lstchain 
- easier for user that just want to load the param table
not related (but I was lazy to make another PR sorry):
- fix the ctaplot import that is not in the requirements with a try
=> params keys in io

.github/release-drafter.yml
See https://github.com/apps/release-drafter
That's what is currently used in ctapipe.
=> adding a release drafter file to keep track of changes

lstchain/io/io.py
=> correct path for images in DL1 files

.travis.yml
=> testing only lstchain

lstchain/calib/camera/r0.py
Hi,
After discuss with @SeiyaNozaki, I realized that conditions in 'time_lapse_corr' should be a bit different.
So, I have changed conditions as I understood.
Dear @SeiyaNozaki,
Could you check if this version is correct?
Dear @rlopezcoto ,
I am sorry for mess, but now this is only small change in code in 3 places
=> Improved condition in time lapse corr

lstchain/image/muon/muon_analysis.py, scripts/lstchain_data_muon_analysis.py
I added an image size based muon tagging function in the muon module (muon_analysis.py).
It is called in the script lstchain_data_muon_analysis.py with the default values, i.e. no tagging.
=> Muon tagging

lstchain/scripts/onsite/onsite_create_calibration_file.py, lstchain/scripts/onsite/onsite_create_drs4_pedestal_file.py, lstchain/visualization/plot_calib.py
Simple changes to improve calibration plot axis
=> Improve plot

lstchain/image/muon/muon_analysis.py
=> solve tailcuts bug

lstchain/calib/camera/time_correction_calculate.py
`hf.close()` is failing in case try failed
=> fix bug with file close

lstchain/io/io.py
=> reading mcheader from merged files with units

lstchain/conftest.py, lstchain/reco/r0_to_dl1.py
@rlopezcoto does this fix you issue?
=> Write array_info before opening hdfwriter

lstchain/scripts/lstchain_data_create_drs4_pedestal_file.py, lstchain/scripts/onsite/onsite_create_drs4_pedestal_file.py
I changed the default number of events for drs4 pedestal table from 8k to 20k.
See #336
=> change default max_events from 8k to 20k for drs4 pedestal table creation

lstchain/scripts/lstchain_add_source_dependent_parameters.py, lstchain/scripts/lstchain_data_create_drs4_pedestal_file.py, lstchain/scripts/lstchain_data_create_time_calibration_file.py, lstchain/scripts/lstchain_data_r0_to_dl1.py, lstchain/scripts/lstchain_dl1_muon_analysis.py, lstchain/scripts/lstchain_dl1_to_dl2.py, lstchain/scripts/lstchain_mc_dl1ab.py, lstchain/scripts/lstchain_mc_r0_to_dl1.py, lstchain/scripts/lstchain_mc_r0_to_dl2.py, lstchain/scripts/lstchain_mc_rfperformance.py, lstchain/scripts/lstchain_mc_sensitivity.py, lstchain/scripts/lstchain_mc_trainpipe.py, lstchain/scripts/lstchain_merge_hdf5_files.py, lstchain/scripts/tests/test_lstchain_scripts.py
Working out #378, this will break several scripts calling these ones, but some unification was needed... 
If you have other suggestions for the variable, please let me know, otherwise I'll continue for the rest of them.
=> Rename variables inside scripts

lstchain/scripts/lstchain_dl1_to_dl2.py, lstchain/scripts/tests/test_lstchain_scripts.py
Substitutes #375 (that fixes #372) in which I messed with the history of the repo...
=> Write DL2 files without images

lstchain/calib/camera/calibration_calculator.py, lstchain/calib/camera/flatfield.py, lstchain/calib/camera/pedestals.py, lstchain/reco/r0_to_dl1.py
Two corrections:
- correct the configuration given to the calibration calculator, at present the flat-field and pedestal Component do not get the correct cards
- Check that some statistic is collected (at least one event) before storing the interleaved results
=> Fix interleaved events code

lstchain/calib/camera/calibration_calculator.py, lstchain/calib/camera/flatfield.py, lstchain/calib/camera/pedestals.py
- added the test of UCTS trigger type for pedestals
- added the test of the collected statistics (at least > 0) before calculating the calibration values
=> Fix to make calibration code more robust in case of missing data

lstchain/reco/utils.py
Parameters with `inf` values should also be removed by default.
=> filtering also inf params

lstchain/visualization/plot_dl2.py, lstchain/visualization/tests/test_plot_dl2.py
=> fix bug in plot feature importance when figure already exists

lstchain/scripts/benchmarks/charge_benchmark.py, setup.py
Benchmark script to check calibration.
Make the following plots:
=> add benchmark charge script

lstchain/reco/tests/test_utils.py, lstchain/reco/utils.py
This PR introduces the function(`radec_to_camera`) to convert from sky coordinate(RA/Dec) to camera coordinate.
After this PR, I'd like to improve the codes for source-dependent analysis with wobble observation.
=> introduce radec_to_camera function

.travis.yml, environment.yml
=> bump ctapipe_io_lst version

.travis.yml
Necessary for tests
Remember to reset `lst-dev` in `.travis.yml` and `environment.yml` before merging the whole branch to master.
=> travis env update for tests to pass with the temporary environment

lstchain/data/lstchain_src_dep_config.json, lstchain/data/lstchain_standard_config.json, lstchain/data/soft_cut_config.json, lstchain/io/lstcontainers.py, lstchain/mc/sensitivity.py, lstchain/reco/utils.py, lstchain/scripts/lstchain_mc_dl1ab.py
From https://github.com/cta-observatory/ctapipe/pull/1123
=> Rename concentration and leakage containers

lstchain/calib/camera/calibrator.py, lstchain/calib/camera/r0.py, lstchain/calib/camera/tests/test_flatfield.py, lstchain/reco/r0_to_dl1.py
Include things  from #474 - should come after  it.
To be discussed, there must be a better way to handle this.
Resolve issue #482
=> Image Extractor

.travis.yml
=> Revert environment in travis

lstchain/image/muon/muon_analysis.py, lstchain/scripts/lstchain_dl1_muon_analysis.py
Useful feature until we move to a full ctapipe-based muon analysis (see #438)
=> Add energy to muon tables

lstchain/image/muon/muon_analysis.py, lstchain/reco/r0_to_dl1.py
For the real data case a recently added argument (only used for MC) was missing.
=> Fixed wrong arguments in call to fill_muon_event

.github/workflows/ci.yml, README.md, download_test_data.sh, lstchain/conftest.py, lstchain/tests/test_lstchain.py
I added the necessary credentials to the repository secrets and also added a small example test showing how to use it.
=> Download the private test data

lstchain/mc/plot_utils.py, lstchain/mc/sensitivity.py, lstchain/mc/tests/test_senstivity.py, lstchain/scripts/lstchain_mc_sensitivity.py, lstchain/tests/test_lstchain.py
Adapted #532  to current master version, I closed the old PR and created this one following the current procedure.
=> lstchain-sensitivity tools refactoring

lstchain/reco/tests/test_utils.py, lstchain/reco/utils.py
And always return times in seconds in any case
=> Make get_effective_time accept QTable as input

lstchain/mc/sensitivity.py, lstchain/mc/tests/test_senstivity.py
Sorry for open other PR, forgot to substitute the old function for the new effective time function.
=> Use new function for effective time in sensitivity code

lstchain/datachecks/dl1_checker.py
=> Set rate axis in log scale, so that rate of pedestals and flatfields is visible

lstchain/io/__init__.py, lstchain/io/io.py, lstchain/reco/r0_to_dl1.py
Should fix #635, @moralejo can you confirm?
=> Add compression filters to auto_merge_hdf5, use zstd filters by default

setup.py
While a more definitive solution like that proposed in #642 is implemented, this is needed by LSTOSA
=> Add onsite_camera_calibration_param.json to package_data

lstchain/io/io.py, lstchain/scripts/lstchain_merge_hdf5_files.py
@morcuended Can you try this out?
=> Convert table dtype to dtype of merge table before appending, fixes 671

lstchain/calib/camera/time_correction_calculate.py
* Better error message when not enough data is present
* Not catching the error when trying to write the hdf5 file
=> Improve error handling in TimeCorrectionCalculate

lstchain/io/__init__.py, setup.py
Remove some redundant lines left from a previous PR
=> Remove redundant lines

lstchain/reco/r0_to_dl1.py
Should fix the issue reported here https://github.com/cta-observatory/cta-lstchain/issues/684#issuecomment-817278965
=> Fix r0 to dl0 for no events in source

lstchain/scripts/longterm_dl1_check.py
Removed the plot on the position of the low-gain peak in muon events (now meaningless, since no longer available with gain selection in io_lst)
=> Removed plot that is no longer meaningful

lstchain/irf/tests/test_hdus.py, lstchain/reco/r0_to_dl1.py
* Move writer setup / excludes out of the event loop
* Write images before parameter calculations
=> Refactor dl1 writing

lstchain/irf/hdu_table.py
Using the first event for pointing position, instead of a mean value to have the correct pointing position compared with the target source position.
=> Fix pointing in DL3 Pointing HDU

lstchain/image/cleaning.py, lstchain/reco/r0_to_dl1.py
=> Use apply_time_delta_cleaning from current ctapipe master

lstchain/data/lstchain_standard_config.json, lstchain/scripts/lstchain_dl1ab.py
I have add code to dynamic cleaning in `lstchain_dl1ab.py`
To run script with dynamic cleaning:
`python $script_path -f $input_file -o $output_file -c $config_file --pedestal-cleaning True --dynamic-cleaning True`
What do think about my solution? (@moralejo  , @rlopezcoto  , @jsitarek  )
=> Dynamic cleaning

lstchain/data/lstchain_standard_config.json
Changed dynamic cleaning settings to slightly tighter ones.
=> New default dynamic cleaning settings

lstchain/io/lstcontainers.py, lstchain/reco/r0_to_dl1.py, lstchain/scripts/lstchain_dl1ab.py
Adding width and length uncertainties already calculated by ctapipe to lstcontainers and r0_to_dl0 script
=> Updating lstcontainers and r0_to_dl1 to add Hillas uncertainties fields

.github/workflows/ci.yml, environment.yml, lstchain/calib/camera/tests/test_calib.py, lstchain/image/cleaning.py, lstchain/io/tests/test_io.py, lstchain/reco/r0_to_dl1.py, lstchain/scripts/lstchain_data_create_drs4_pedestal_file.py, lstchain/scripts/lstchain_dl1ab.py, setup.py
* ctapipe -> 0.11.0
* ctapipe_io_lst -> 0.11.1
* pyirf -> 0.5
Only some tests needed minor adjustments.
=> Update dependencies, including ctapipe to 0.11.0

lstchain/reco/utils.py
No longer used and not tested.
```python
@deprecated(
"09/07/2019",
message="This is a custom implementation. Use `sky_to_camera` that relies on astropy",
)
def cal_cam_source_pos(mc_alt, mc_az, mc_alt_tel, mc_az_tel, focal_length):
```
=> Remove deprecated and unused function

lstchain/scripts/onsite/onsite_create_drs4_time_file.py
=> Remove 2>&1 from time calibration onsite command

lstchain/data/onsite_camera_calibration_param.json
Indentation in the file was completely messed up
=> Fix indentation in config file

docs/conf.py
For proper docs deployment, add a .nojekyll file
=> Add sphinx.ext.githubpages to docs config

environment.yml, lstchain/mc/plot_utils.py, setup.py
current master is failing due to this
=> fix issue with nonposx

lstchain/reco/r0_to_dl1.py, lstchain/scripts/lstchain_dl1ab.py
This allows keeping track of the applied mask to compute the parameters.
=> Save clean mask in DL1 files

lstchain/scripts/onsite/onsite_create_calibration_file.py, lstchain/scripts/onsite/onsite_create_calibration_files_with_batch.py, lstchain/scripts/onsite/onsite_create_drs4_pedestal_file.py, lstchain/scripts/onsite/onsite_create_drs4_time_file.py, lstchain/scripts/onsite/onsite_create_ffactor_systematics_file.py
=> Do not catch all exceptions in onsite scripts, use exit codes != 0

lstchain/scripts/onsite/onsite_create_calibration_file.py, lstchain/scripts/onsite/onsite_create_calibration_files_with_batch.py, lstchain/scripts/onsite/onsite_create_drs4_pedestal_file.py, lstchain/scripts/onsite/onsite_create_drs4_time_file.py, lstchain/scripts/onsite/onsite_create_ffactor_systematics_file.py
Reverts cta-observatory/cta-lstchain#804
@FrancaCassol asked to revert this because she was unable to resolve the merge conflicts this created with #776
=> Revert "Do not catch all exceptions in onsite scripts, use exit codes != 0"

lstchain/io/io.py, lstchain/scripts/lstchain_data_create_drs4_pedestal_file.py, lstchain/scripts/lstchain_data_create_time_calibration_file.py, lstchain/scripts/lstchain_merge_hdf5_files.py
This is very convenient to avoid having in the job analysis log a lot of not practical noisy lines.
=> Add option to display progress bar to avoid showing it when running in batch mode

.github/workflows/ci.yml
=> Use mamba to create conda env in CI

lstchain/scripts/onsite/onsite_create_calibration_file.py, lstchain/scripts/onsite/onsite_create_drs4_pedestal_file.py, lstchain/scripts/onsite/onsite_create_drs4_time_file.py, lstchain/scripts/onsite/onsite_create_ffactor_systematics_file.py
Follow up for the reverted merge request that already did this before.
This time, no other changes than the remove  try / catch were made. I will do some more PRs with cleanup for the onsite scripts
=> Do not catch all exceptions in onsite scripts

lstchain/visualization/plot_drs4.py
Fix for the issue reported by @morcuended in slack
Plots for the test run are looking like this again now:
=> Fix drs4 pedestal plots

.github/workflows/ci.yml, lstchain/reco/tests/test_utils.py, lstchain/reco/utils.py, lstchain/scripts/longterm_dl1_check.py, lstchain/scripts/lstchain_find_pedestals.py, lstchain/scripts/onsite/onsite_create_calibration_file.py, lstchain/scripts/onsite/onsite_create_drs4_pedestal_file.py, lstchain/scripts/onsite/onsite_create_drs4_time_file.py, lstchain/scripts/onsite/onsite_create_ffactor_systematics_file.py, lstchain/scripts/tests/test_lstchain_scripts.py, lstchain/tools/tests/test_create_drs4_pedestal_file.py
The yml was missing a line continuation character and that is why pyflakes was not actually run in the CI.
Fixed and also fixed some issues that were found now.
=> Fix pyflakes check in CI and fix issues

docs/introduction.rst, docs/lstchain_api/image/index.rst, lstchain/image/cleaning.py, lstchain/image/modifier.py, lstchain/image/muon/muon_analysis.py, lstchain/image/muon/plot_muon.py
For the LST analysis school, I included documentation regarding:
* Muon analysis
* Standard analysis steps and dependencies
=> Docs improvements

lstchain/scripts/lstchain_dl1_muon_analysis.py
The muon script was not working to analyze real data, this fixes it
=> Fix muon script for real data

lstchain/scripts/longterm_dl1_check.py
=> typo in comment

setup.py
=> Fix pyirf version in setup.py

lstchain/scripts/lstchain_longterm_dl1_check.py, lstchain/visualization/bokeh.py
Just a minor addition. Shows in graphical form the information written out to the log about pixels which have parameters beyond certain limits.
=> Added tab "Pixel problems" with a summary of issues detected in pixels

lstchain/scripts/lstchain_longterm_dl1_check.py
Script did not work in case some runs had no flatfield events or no muon rings.
=> Solved DL1 check issues

lstchain/onsite.py, lstchain/paths.py, lstchain/scripts/onsite/onsite_create_calibration_file.py, lstchain/scripts/onsite/onsite_create_calibration_files_with_batch.py, lstchain/scripts/onsite/onsite_create_drs4_pedestal_file.py, lstchain/scripts/onsite/onsite_create_drs4_time_file.py, lstchain/scripts/onsite/onsite_create_ffactor_systematics_file.py, lstchain/tests/test_onsite.py
* Use `Path` in `create_pro_symlink`, add test
* Factor out functions to find R0 subruns, pedestal files, time calibration files, run summaries and add tests
=> Refactor onsite scripts

lstchain/data/lstchain_standard_config.json
Same as #925 -  I think that has been the actual standard for a while now...
=> tailcut to 8-4 as standard config

notebooks/data_selection.ipynb
Uses the output of the DL1 data check
=> Added notebook for the selection of runs for analysis

lstchain/datachecks/containers.py, lstchain/scripts/lstchain_longterm_dl1_check.py, lstchain/visualization/bokeh.py
=> Fixes in DL1 data check

environment.yml, lstchain/conftest.py, lstchain/scripts/lstchain_data_create_time_calibration_file.py, lstchain/scripts/lstchain_data_r0_to_dl1.py, lstchain/scripts/onsite/onsite_create_calibration_file.py, lstchain/scripts/onsite/onsite_create_calibration_files_with_batch.py, lstchain/scripts/onsite/onsite_create_drs4_time_file.py, setup.py
Adding a switch to disable the flatfield heuristic in the onsite scripts that need it
=> Update ctapipe_io_lst and add `--flatfield-heuristic` switch to relevant programs

lstchain/calib/camera/calibration_calculator.py, lstchain/scripts/onsite/onsite_create_calibration_file.py, lstchain/tools/lstchain_create_calibration_file.py
Makes it easier to directly use this tool
=> Calib aliases

lstchain/mc/__init__.py, lstchain/mc/sensitivity.py, lstchain/mc/tests/test_senstivity.py
Fixed sensitivity formula (it seems it is not used anywhere, but just in case)
=> Remove obsolete sensitivity function

lstchain/data/lstchain_standard_config.json, lstchain/io/lstcontainers.py, lstchain/reco/r0_to_dl1.py
=> compute and use sin of pointing

README.md
Adds the Zenodo badge on top and a _Cite_ section to cite from Zenodo
=> Add Cite to README

lstchain/image/muon/muon_analysis.py
Fixed wrong type description of output  in analyze_muon_event
=> Fix analyze_muon_event function description

lstchain/reco/reconstructor.py, lstchain/reco/reconstructorCC.py, lstchain/scripts/numba_compil_lhfit.py, lstchain/scripts/tests/test_lstchain_scripts.py, lstchain/tests/test_lstchain.py, lstchain/visualization/plot_reconstructor.py, setup.py
This brings us back to a pure python distribution, fixing the wheel upload to pypi
=> Remove numba aot compilation, use njit instead

lstchain/scripts/lstchain_dl1ab.py
Allows to get DL1 file with the sin_az_tel parameter just running the DL1ab script.
=> Recalculate sin_az_tel

lstchain/scripts/onsite/onsite_create_drs4_pedestal_file.py
=> Fix argument handling in onsite_create_drs4_pedestal_file, fixes #1046

lstchain/scripts/lstchain_dl1_to_dl2.py, lstchain/scripts/tests/test_lstchain_scripts.py
=> allow a list of dl1 files to be passed to lstchain_dl1_to_dl2

lstchain/io/lstcontainers.py
Initiated to solve #504. Also uniformised use of capital letters at the start of parameter descriptions.
closes #504
=> Solve a typo and uniformise use of capital letters

environment.yml, setup.py
=> fixing joblib version to 1.2

lstchain/conftest.py
=> Correct config.option.markexpr autocompletion

.github/workflows/ci.yml, environment.yml, lstchain/reco/dl1_to_dl2.py, lstchain/reco/utils.py
Solves breaking changes in the new version of pandas
Closes #1083
=> Update pandas usage to 2.0.0

docs/introduction.rst
=> forgot docs intro change

environment.yml, setup.py
=> Specify scipy dependency to be above v1.8

.github/workflows/ci.yml, environment.yml, lstchain/ctapipe_compat.py, lstchain/image/muon/muon_analysis.py, setup.cfg, setup.py
Try updating to 0.18, needs release of the source first, so just draft for now
=> update ctapipe to 0.18

lstchain/calib/camera/calibration_calculator.py
The bug correction of [https://github.com/cta-observatory/cta-lstchain/pull/1104](https://github.com/cta-observatory/cta-lstchain/pull/1104) has been overwritten in a successive merge
=> Correct unusable pixel definition again

lstchain/scripts/lstchain_create_run_summary.py
=> Get run type from TCU if it's available

README.md
Update some general outdated information
=> Update general information in README.md

notebooks/data_quality.ipynb
Minor bug fix in data_quality.ipynb
=> Fixed two bugs in 'data_quality' notebook

lstchain/scripts/lstchain_r0g_to_r0v.py
For interleaved events, the event status was not properly updated!
=> Fix lstchain_r0g_to_r0v.py

lstchain/reco/tests/test_utils.py, lstchain/reco/utils.py
Make it consistent with the event selection of the DL2 to DL3 stage. Effect is very small anyway except for rare runs.
=> Update eff. time computation

lstchain/io/io.py, lstchain/scripts/lstchain_merge_hdf5_files.py
=> Do not merge nor copy monitoring tables when merging DL1 h5 files

README.md
* Use ADASS reference instead of ICRC2021
see #1205
=> Update lstchain citation in README

download_test_data.sh
We had technical issues in Dortmund with the server hosting the lst test data.
I moved them to another server, update the URLs here.
It would really be great if we could find an LST solution for this.
=> Update test-data url

docs/introduction.rst
=> Add references for special analyses (pulsar, extended source)

lstchain/reco/r0_to_dl1.py
The option to scale the DL1a charges in MC images was no longer working.
=> MC charge scaling factor

lstchain/scripts/lstchain_dl1ab.py
Convert pedestal cleaning threshold (for the Cat-B case) from counts to p.e.
=> Pedestal cleaning for Cat-B
